// Auto-generated by Playmix fetch_weather.py
// Refreshed daily via GitHub Actions at 2:00 AM UTC (7:30 AM IST)
// Do NOT edit manually — changes will be overwritten by the next fetch.
window.WEATHER_DATA = {
  "generated_at": "2026-04-19T10:00:00Z",
  "countries": {
    "IN": { "name":"India","code":"IN","lat":20.59,"lon":78.96,"zoom":5,"flag":"\ud83c\uddee\ud83c\uddf3","temp":38,"code_w":1,"precip":0,"snow":0,"wind":18,"icon":"\u26c5" },
    "US": { "name":"USA","code":"US","lat":37.09,"lon":-95.71,"zoom":5,"flag":"\ud83c\uddfa\ud83c\uddf8","temp":16,"code_w":2,"precip":0,"snow":0,"wind":22,"icon":"\u26c5" },
    "BR": { "name":"Brazil","code":"BR","lat":-14.23,"lon":-51.93,"zoom":5,"flag":"\ud83c\udde7\ud83c\uddf7","temp":28,"code_w":80,"precip":3.2,"snow":0,"wind":14,"icon":"\ud83c\udf27\ufe0f" },
    "CN": { "name":"China","code":"CN","lat":35.86,"lon":104.19,"zoom":5,"flag":"\ud83c\udde8\ud83c\uddf3","temp":17,"code_w":2,"precip":0,"snow":0,"wind":20,"icon":"\u26c5" },
    "RU": { "name":"Russia","code":"RU","lat":61.52,"lon":105.32,"zoom":4,"flag":"\ud83c\uddf7\ud83c\uddfa","temp":-3,"code_w":71,"precip":0,"snow":2.1,"wind":12,"icon":"\u2744\ufe0f" },
    "AU": { "name":"Australia","code":"AU","lat":-25.27,"lon":133.78,"zoom":5,"flag":"\ud83c\udde6\ud83c\uddfa","temp":24,"code_w":0,"precip":0,"snow":0,"wind":25,"icon":"\u2600\ufe0f" },
    "DE": { "name":"Germany","code":"DE","lat":51.17,"lon":10.45,"zoom":6,"flag":"\ud83c\udde9\ud83c\uddea","temp":14,"code_w":3,"precip":0,"snow":0,"wind":30,"icon":"\u2601\ufe0f" },
    "FR": { "name":"France","code":"FR","lat":46.23,"lon":2.21,"zoom":6,"flag":"\ud83c\uddeb\ud83c\uddf7","temp":16,"code_w":1,"precip":0,"snow":0,"wind":18,"icon":"\u26c5" },
    "JP": { "name":"Japan","code":"JP","lat":36.20,"lon":138.25,"zoom":6,"flag":"\ud83c\uddef\ud83c\uddf5","temp":18,"code_w":2,"precip":0,"snow":0,"wind":16,"icon":"\u26c5" },
    "GB": { "name":"UK","code":"GB","lat":55.38,"lon":-3.44,"zoom":6,"flag":"\ud83c\uddec\ud83c\udde7","temp":11,"code_w":61,"precip":1.2,"snow":0,"wind":28,"icon":"\ud83c\udf27\ufe0f" },
    "CA": { "name":"Canada","code":"CA","lat":56.13,"lon":-106.35,"zoom":4,"flag":"\ud83c\udde8\ud83c\udde6","temp":-5,"code_w":73,"precip":0,"snow":3.0,"wind":15,"icon":"\u2744\ufe0f" },
    "MX": { "name":"Mexico","code":"MX","lat":23.63,"lon":-102.55,"zoom":6,"flag":"\ud83c\uddf2\ud83c\uddfd","temp":26,"code_w":0,"precip":0,"snow":0,"wind":20,"icon":"\u2600\ufe0f" },
    "ZA": { "name":"South Africa","code":"ZA","lat":-30.56,"lon":22.94,"zoom":6,"flag":"\ud83c\uddff\ud83c\udde6","temp":21,"code_w":1,"precip":0,"snow":0,"wind":22,"icon":"\u26c5" },
    "EG": { "name":"Egypt","code":"EG","lat":26.82,"lon":30.80,"zoom":7,"flag":"\ud83c\uddea\ud83c\uddec","temp":34,"code_w":0,"precip":0,"snow":0,"wind":19,"icon":"\u2600\ufe0f" },
    "NG": { "name":"Nigeria","code":"NG","lat":9.08,"lon":8.68,"zoom":7,"flag":"\ud83c\uddf3\ud83c\uddec","temp":33,"code_w":80,"precip":4.1,"snow":0,"wind":16,"icon":"\ud83c\udf27\ufe0f" },
    "ID": { "name":"Indonesia","code":"ID","lat":-0.79,"lon":113.92,"zoom":5,"flag":"\ud83c\uddee\ud83c\udde9","temp":31,"code_w":80,"precip":5.5,"snow":0,"wind":12,"icon":"\ud83c\udf27\ufe0f" },
    "AR": { "name":"Argentina","code":"AR","lat":-38.42,"lon":-63.62,"zoom":5,"flag":"\ud83c\udde6\ud83c\uddf7","temp":12,"code_w":1,"precip":0,"snow":0,"wind":30,"icon":"\u26c5" },
    "SA": { "name":"Saudi Arabia","code":"SA","lat":23.886,"lon":45.08,"zoom":6,"flag":"\ud83c\uddf8\ud83c\udde6","temp":40,"code_w":0,"precip":0,"snow":0,"wind":24,"icon":"\u2600\ufe0f" },
    "TR": { "name":"Turkey","code":"TR","lat":38.96,"lon":35.24,"zoom":6,"flag":"\ud83c\uddf9\ud83c\uddf7","temp":20,"code_w":2,"precip":0,"snow":0,"wind":20,"icon":"\u26c5" },
    "IT": { "name":"Italy","code":"IT","lat":41.87,"lon":12.57,"zoom":6,"flag":"\ud83c\uddee\ud83c\uddf9","temp":19,"code_w":1,"precip":0,"snow":0,"wind":15,"icon":"\u26c5" },
    "ES": { "name":"Spain","code":"ES","lat":40.46,"lon":-3.75,"zoom":6,"flag":"\ud83c\uddea\ud83c\uddf8","temp":22,"code_w":0,"precip":0,"snow":0,"wind":18,"icon":"\u2600\ufe0f" },
    "KR": { "name":"South Korea","code":"KR","lat":35.91,"lon":127.77,"zoom":7,"flag":"\ud83c\uddf0\ud83c\uddf7","temp":16,"code_w":2,"precip":0,"snow":0,"wind":14,"icon":"\u26c5" },
    "PK": { "name":"Pakistan","code":"PK","lat":30.38,"lon":69.35,"zoom":6,"flag":"\ud83c\uddf5\ud83c\uddf0","temp":36,"code_w":0,"precip":0,"snow":0,"wind":22,"icon":"\u2600\ufe0f" },
    "BD": { "name":"Bangladesh","code":"BD","lat":23.68,"lon":90.36,"zoom":8,"flag":"\ud83c\udde7\ud83c\udde9","temp":34,"code_w":80,"precip":2.8,"snow":0,"wind":14,"icon":"\ud83c\udf27\ufe0f" },
    "VN": { "name":"Vietnam","code":"VN","lat":14.06,"lon":108.28,"zoom":7,"flag":"\ud83c\uddfb\ud83c\uddf3","temp":29,"code_w":80,"precip":1.5,"snow":0,"wind":16,"icon":"\ud83c\udf27\ufe0f" },
    "TH": { "name":"Thailand","code":"TH","lat":15.87,"lon":100.99,"zoom":7,"flag":"\ud83c\uddf9\ud83c\udded","temp":33,"code_w":1,"precip":0,"snow":0,"wind":12,"icon":"\u26c5" },
    "NL": { "name":"Netherlands","code":"NL","lat":52.13,"lon":5.29,"zoom":8,"flag":"\ud83c\uddf3\ud83c\uddf1","temp":12,"code_w":61,"precip":0.8,"snow":0,"wind":35,"icon":"\ud83c\udf27\ufe0f" },
    "UA": { "name":"Ukraine","code":"UA","lat":48.38,"lon":31.17,"zoom":6,"flag":"\ud83c\uddfa\ud83c\udde6","temp":13,"code_w":2,"precip":0,"snow":0,"wind":18,"icon":"\u26c5" },
    "PL": { "name":"Poland","code":"PL","lat":51.92,"lon":19.14,"zoom":7,"flag":"\ud83c\uddf5\ud83c\uddf1","temp":10,"code_w":3,"precip":0,"snow":0,"wind":22,"icon":"\u2601\ufe0f" },
    "SE": { "name":"Sweden","code":"SE","lat":60.13,"lon":18.64,"zoom":6,"flag":"\ud83c\uddf8\ud83c\uddea","temp":5,"code_w":1,"precip":0,"snow":0,"wind":16,"icon":"\u26c5" }
  },
  "states": {
    "IN": [
      {"name":"Maharashtra","lat":19.75,"lon":75.71,"temp":37,"code":1,"precip":0,"snow":0,"wind":20,"icon":"\u26c5"},
      {"name":"Delhi","lat":28.70,"lon":77.10,"temp":40,"code":0,"precip":0,"snow":0,"wind":18,"icon":"\u2600\ufe0f"},
      {"name":"Karnataka","lat":15.32,"lon":75.71,"temp":32,"code":1,"precip":0,"snow":0,"wind":16,"icon":"\u26c5"},
      {"name":"Tamil Nadu","lat":11.13,"lon":78.66,"temp":35,"code":80,"precip":3.0,"snow":0,"wind":22,"icon":"\ud83c\udf27\ufe0f"},
      {"name":"West Bengal","lat":22.99,"lon":87.85,"temp":33,"code":80,"precip":2.5,"snow":0,"wind":14,"icon":"\ud83c\udf27\ufe0f"},
      {"name":"Gujarat","lat":22.26,"lon":71.19,"temp":38,"code":0,"precip":0,"snow":0,"wind":24,"icon":"\u2600\ufe0f"},
      {"name":"Rajasthan","lat":27.02,"lon":74.22,"temp":42,"code":0,"precip":0,"snow":0,"wind":26,"icon":"\u2600\ufe0f"},
      {"name":"Uttar Pradesh","lat":26.85,"lon":80.91,"temp":39,"code":0,"precip":0,"snow":0,"wind":20,"icon":"\u2600\ufe0f"}
    ],
    "US": [
      {"name":"California","lat":36.78,"lon":-119.42,"temp":22,"code":0,"precip":0,"snow":0,"wind":18,"icon":"\u2600\ufe0f"},
      {"name":"Texas","lat":31.97,"lon":-99.90,"temp":28,"code":1,"precip":0,"snow":0,"wind":24,"icon":"\u26c5"},
      {"name":"New York","lat":42.17,"lon":-74.95,"temp":10,"code":61,"precip":1.2,"snow":0,"wind":30,"icon":"\ud83c\udf27\ufe0f"},
      {"name":"Florida","lat":27.99,"lon":-81.76,"temp":29,"code":80,"precip":4.0,"snow":0,"wind":20,"icon":"\ud83c\udf27\ufe0f"},
      {"name":"Illinois","lat":40.35,"lon":-88.99,"temp":12,"code":2,"precip":0,"snow":0,"wind":28,"icon":"\u26c5"},
      {"name":"Washington","lat":47.75,"lon":-120.74,"temp":11,"code":61,"precip":2.0,"snow":0,"wind":22,"icon":"\ud83c\udf27\ufe0f"}
    ],
    "GB": [
      {"name":"England","lat":52.35,"lon":-1.17,"temp":11,"code":61,"precip":1.5,"snow":0,"wind":32,"icon":"\ud83c\udf27\ufe0f"},
      {"name":"Scotland","lat":56.49,"lon":-4.20,"temp":7,"code":73,"precip":0.5,"snow":1.0,"wind":40,"icon":"\u2744\ufe0f"},
      {"name":"Wales","lat":52.13,"lon":-3.78,"temp":10,"code":61,"precip":2.0,"snow":0,"wind":35,"icon":"\ud83c\udf27\ufe0f"}
    ],
    "AU": [
      {"name":"New South Wales","lat":-32.16,"lon":147.02,"temp":21,"code":0,"precip":0,"snow":0,"wind":18,"icon":"\u2600\ufe0f"},
      {"name":"Victoria","lat":-36.85,"lon":144.28,"temp":17,"code":2,"precip":0,"snow":0,"wind":22,"icon":"\u26c5"},
      {"name":"Queensland","lat":-22.57,"lon":144.08,"temp":28,"code":80,"precip":3.5,"snow":0,"wind":16,"icon":"\ud83c\udf27\ufe0f"},
      {"name":"Western Australia","lat":-25.33,"lon":122.03,"temp":26,"code":0,"precip":0,"snow":0,"wind":20,"icon":"\u2600\ufe0f"}
    ],
    "JP": [
      {"name":"Tokyo","lat":35.69,"lon":139.69,"temp":18,"code":1,"precip":0,"snow":0,"wind":16,"icon":"\u26c5"},
      {"name":"Osaka","lat":34.67,"lon":135.50,"temp":19,"code":1,"precip":0,"snow":0,"wind":14,"icon":"\u26c5"},
      {"name":"Hokkaido","lat":43.46,"lon":142.83,"temp":5,"code":61,"precip":1.0,"snow":0,"wind":22,"icon":"\ud83c\udf27\ufe0f"},
      {"name":"Fukuoka","lat":33.56,"lon":130.72,"temp":20,"code":0,"precip":0,"snow":0,"wind":14,"icon":"\u2600\ufe0f"}
    ],
    "DE": [
      {"name":"Bavaria","lat":48.79,"lon":11.50,"temp":12,"code":2,"precip":0,"snow":0,"wind":18,"icon":"\u26c5"},
      {"name":"Berlin","lat":52.52,"lon":13.40,"temp":14,"code":3,"precip":0,"snow":0,"wind":24,"icon":"\u2601\ufe0f"},
      {"name":"NRW","lat":51.43,"lon":7.66,"temp":13,"code":61,"precip":0.9,"snow":0,"wind":30,"icon":"\ud83c\udf27\ufe0f"}
    ],
    "FR": [
      {"name":"Ile-de-France","lat":48.85,"lon":2.35,"temp":15,"code":2,"precip":0,"snow":0,"wind":20,"icon":"\u26c5"},
      {"name":"Provence","lat":43.83,"lon":5.71,"temp":20,"code":0,"precip":0,"snow":0,"wind":22,"icon":"\u2600\ufe0f"},
      {"name":"Auvergne","lat":45.75,"lon":3.07,"temp":14,"code":1,"precip":0,"snow":0,"wind":18,"icon":"\u26c5"}
    ],
    "CN": [
      {"name":"Beijing","lat":39.91,"lon":116.39,"temp":18,"code":2,"precip":0,"snow":0,"wind":20,"icon":"\u26c5"},
      {"name":"Shanghai","lat":31.23,"lon":121.47,"temp":20,"code":1,"precip":0,"snow":0,"wind":16,"icon":"\u26c5"},
      {"name":"Guangdong","lat":23.37,"lon":113.50,"temp":28,"code":80,"precip":4.0,"snow":0,"wind":18,"icon":"\ud83c\udf27\ufe0f"},
      {"name":"Sichuan","lat":30.65,"lon":102.71,"temp":16,"code":2,"precip":0,"snow":0,"wind":12,"icon":"\u26c5"}
    ],
    "BR": [
      {"name":"Sao Paulo","lat":-23.55,"lon":-46.63,"temp":24,"code":80,"precip":4.5,"snow":0,"wind":14,"icon":"\ud83c\udf27\ufe0f"},
      {"name":"Rio de Janeiro","lat":-22.91,"lon":-43.17,"temp":30,"code":1,"precip":0,"snow":0,"wind":20,"icon":"\u26c5"},
      {"name":"Amazonas","lat":-3.07,"lon":-60.01,"temp":32,"code":80,"precip":8.0,"snow":0,"wind":10,"icon":"\ud83c\udf27\ufe0f"},
      {"name":"Bahia","lat":-12.97,"lon":-38.51,"temp":30,"code":80,"precip":2.5,"snow":0,"wind":18,"icon":"\ud83c\udf27\ufe0f"}
    ]
  },
  "cities": {
    "IN": {
      "Maharashtra": [
        {"name":"Mumbai","lat":19.07,"lon":72.87,"temp":33,"code":80,"precip":1.5,"snow":0,"wind":22,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Pune","lat":18.52,"lon":73.85,"temp":36,"code":1,"precip":0,"snow":0,"wind":18,"icon":"\u26c5"},
        {"name":"Nagpur","lat":21.14,"lon":79.09,"temp":40,"code":0,"precip":0,"snow":0,"wind":16,"icon":"\u2600\ufe0f"}
      ],
      "Delhi": [
        {"name":"New Delhi","lat":28.61,"lon":77.21,"temp":41,"code":0,"precip":0,"snow":0,"wind":20,"icon":"\u2600\ufe0f"},
        {"name":"Noida","lat":28.54,"lon":77.39,"temp":40,"code":0,"precip":0,"snow":0,"wind":18,"icon":"\u2600\ufe0f"},
        {"name":"Gurgaon","lat":28.45,"lon":77.03,"temp":40,"code":0,"precip":0,"snow":0,"wind":22,"icon":"\u2600\ufe0f"}
      ],
      "Karnataka": [
        {"name":"Bengaluru","lat":12.97,"lon":77.59,"temp":28,"code":1,"precip":0,"snow":0,"wind":14,"icon":"\u26c5"},
        {"name":"Mysuru","lat":12.30,"lon":76.65,"temp":30,"code":0,"precip":0,"snow":0,"wind":12,"icon":"\u2600\ufe0f"},
        {"name":"Hubli","lat":15.36,"lon":75.12,"temp":33,"code":0,"precip":0,"snow":0,"wind":18,"icon":"\u2600\ufe0f"}
      ],
      "Tamil Nadu": [
        {"name":"Chennai","lat":13.08,"lon":80.28,"temp":36,"code":1,"precip":0,"snow":0,"wind":24,"icon":"\u26c5"},
        {"name":"Coimbatore","lat":11.02,"lon":76.96,"temp":32,"code":80,"precip":2.0,"snow":0,"wind":16,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Madurai","lat":9.93,"lon":78.12,"temp":37,"code":0,"precip":0,"snow":0,"wind":20,"icon":"\u2600\ufe0f"}
      ],
      "West Bengal": [
        {"name":"Kolkata","lat":22.57,"lon":88.36,"temp":34,"code":80,"precip":3.5,"snow":0,"wind":18,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Howrah","lat":22.59,"lon":88.31,"temp":33,"code":80,"precip":3.0,"snow":0,"wind":16,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Darjeeling","lat":27.04,"lon":88.27,"temp":14,"code":61,"precip":5.0,"snow":0,"wind":22,"icon":"\ud83c\udf27\ufe0f"}
      ],
      "Gujarat": [
        {"name":"Ahmedabad","lat":23.02,"lon":72.57,"temp":40,"code":0,"precip":0,"snow":0,"wind":24,"icon":"\u2600\ufe0f"},
        {"name":"Surat","lat":21.17,"lon":72.83,"temp":35,"code":1,"precip":0,"snow":0,"wind":20,"icon":"\u26c5"},
        {"name":"Vadodara","lat":22.31,"lon":73.18,"temp":39,"code":0,"precip":0,"snow":0,"wind":22,"icon":"\u2600\ufe0f"}
      ],
      "Rajasthan": [
        {"name":"Jaipur","lat":26.91,"lon":75.79,"temp":42,"code":0,"precip":0,"snow":0,"wind":26,"icon":"\u2600\ufe0f"},
        {"name":"Jodhpur","lat":26.29,"lon":73.02,"temp":43,"code":0,"precip":0,"snow":0,"wind":30,"icon":"\u2600\ufe0f"},
        {"name":"Udaipur","lat":24.58,"lon":73.68,"temp":38,"code":0,"precip":0,"snow":0,"wind":20,"icon":"\u2600\ufe0f"}
      ],
      "Uttar Pradesh": [
        {"name":"Lucknow","lat":26.85,"lon":80.95,"temp":39,"code":0,"precip":0,"snow":0,"wind":18,"icon":"\u2600\ufe0f"},
        {"name":"Kanpur","lat":26.47,"lon":80.33,"temp":40,"code":0,"precip":0,"snow":0,"wind":20,"icon":"\u2600\ufe0f"},
        {"name":"Varanasi","lat":25.32,"lon":83.01,"temp":40,"code":0,"precip":0,"snow":0,"wind":16,"icon":"\u2600\ufe0f"}
      ]
    },
    "US": {
      "California": [
        {"name":"Los Angeles","lat":34.05,"lon":-118.24,"temp":24,"code":0,"precip":0,"snow":0,"wind":14,"icon":"\u2600\ufe0f"},
        {"name":"San Francisco","lat":37.77,"lon":-122.42,"temp":16,"code":48,"precip":0,"snow":0,"wind":28,"icon":"\ud83c\udf2b\ufe0f"},
        {"name":"San Diego","lat":32.72,"lon":-117.15,"temp":22,"code":0,"precip":0,"snow":0,"wind":16,"icon":"\u2600\ufe0f"}
      ],
      "Texas": [
        {"name":"Houston","lat":29.76,"lon":-95.37,"temp":30,"code":80,"precip":5.0,"snow":0,"wind":20,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Dallas","lat":32.78,"lon":-96.80,"temp":27,"code":1,"precip":0,"snow":0,"wind":28,"icon":"\u26c5"},
        {"name":"Austin","lat":30.27,"lon":-97.74,"temp":28,"code":0,"precip":0,"snow":0,"wind":22,"icon":"\u2600\ufe0f"}
      ],
      "New York": [
        {"name":"New York City","lat":40.71,"lon":-74.01,"temp":12,"code":61,"precip":2.0,"snow":0,"wind":35,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Buffalo","lat":42.89,"lon":-78.86,"temp":6,"code":73,"precip":0,"snow":3.0,"wind":40,"icon":"\u2744\ufe0f"},
        {"name":"Albany","lat":42.65,"lon":-73.76,"temp":9,"code":61,"precip":1.0,"snow":0,"wind":30,"icon":"\ud83c\udf27\ufe0f"}
      ],
      "Florida": [
        {"name":"Miami","lat":25.78,"lon":-80.21,"temp":32,"code":80,"precip":6.0,"snow":0,"wind":18,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Orlando","lat":28.54,"lon":-81.38,"temp":29,"code":80,"precip":4.5,"snow":0,"wind":16,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Tampa","lat":27.95,"lon":-82.46,"temp":30,"code":1,"precip":0,"snow":0,"wind":20,"icon":"\u26c5"}
      ],
      "Illinois": [
        {"name":"Chicago","lat":41.85,"lon":-87.65,"temp":10,"code":2,"precip":0,"snow":0,"wind":40,"icon":"\u26c5"},
        {"name":"Springfield","lat":39.78,"lon":-89.65,"temp":14,"code":1,"precip":0,"snow":0,"wind":28,"icon":"\u26c5"},
        {"name":"Rockford","lat":42.27,"lon":-89.09,"temp":9,"code":3,"precip":0,"snow":0,"wind":32,"icon":"\u2601\ufe0f"}
      ],
      "Washington": [
        {"name":"Seattle","lat":47.61,"lon":-122.33,"temp":12,"code":61,"precip":3.0,"snow":0,"wind":22,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Spokane","lat":47.66,"lon":-117.43,"temp":10,"code":61,"precip":1.5,"snow":0,"wind":20,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Tacoma","lat":47.25,"lon":-122.44,"temp":12,"code":61,"precip":2.5,"snow":0,"wind":24,"icon":"\ud83c\udf27\ufe0f"}
      ]
    },
    "GB": {
      "England": [
        {"name":"London","lat":51.50,"lon":-0.12,"temp":12,"code":61,"precip":1.8,"snow":0,"wind":30,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Manchester","lat":53.48,"lon":-2.24,"temp":10,"code":61,"precip":2.5,"snow":0,"wind":36,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Birmingham","lat":52.48,"lon":-1.90,"temp":11,"code":61,"precip":2.0,"snow":0,"wind":28,"icon":"\ud83c\udf27\ufe0f"}
      ],
      "Scotland": [
        {"name":"Edinburgh","lat":55.95,"lon":-3.19,"temp":8,"code":61,"precip":1.5,"snow":0.5,"wind":40,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Glasgow","lat":55.86,"lon":-4.25,"temp":7,"code":73,"precip":0,"snow":2.0,"wind":42,"icon":"\u2744\ufe0f"},
        {"name":"Aberdeen","lat":57.15,"lon":-2.11,"temp":6,"code":73,"precip":0,"snow":3.0,"wind":45,"icon":"\u2744\ufe0f"}
      ],
      "Wales": [
        {"name":"Cardiff","lat":51.48,"lon":-3.18,"temp":11,"code":61,"precip":3.0,"snow":0,"wind":32,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Swansea","lat":51.62,"lon":-3.94,"temp":11,"code":61,"precip":2.5,"snow":0,"wind":35,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Newport","lat":51.59,"lon":-2.99,"temp":11,"code":61,"precip":2.0,"snow":0,"wind":30,"icon":"\ud83c\udf27\ufe0f"}
      ]
    },
    "AU": {
      "New South Wales": [
        {"name":"Sydney","lat":-33.87,"lon":151.21,"temp":22,"code":1,"precip":0,"snow":0,"wind":20,"icon":"\u26c5"},
        {"name":"Newcastle","lat":-32.93,"lon":151.78,"temp":21,"code":0,"precip":0,"snow":0,"wind":22,"icon":"\u2600\ufe0f"},
        {"name":"Wollongong","lat":-34.42,"lon":150.89,"temp":20,"code":1,"precip":0,"snow":0,"wind":18,"icon":"\u26c5"}
      ],
      "Victoria": [
        {"name":"Melbourne","lat":-37.81,"lon":144.96,"temp":16,"code":2,"precip":0,"snow":0,"wind":28,"icon":"\u26c5"},
        {"name":"Geelong","lat":-38.15,"lon":144.36,"temp":15,"code":2,"precip":0,"snow":0,"wind":30,"icon":"\u26c5"},
        {"name":"Ballarat","lat":-37.56,"lon":143.87,"temp":12,"code":61,"precip":1.0,"snow":0,"wind":25,"icon":"\ud83c\udf27\ufe0f"}
      ],
      "Queensland": [
        {"name":"Brisbane","lat":-27.47,"lon":153.02,"temp":27,"code":0,"precip":0,"snow":0,"wind":16,"icon":"\u2600\ufe0f"},
        {"name":"Gold Coast","lat":-28.02,"lon":153.40,"temp":26,"code":0,"precip":0,"snow":0,"wind":18,"icon":"\u2600\ufe0f"},
        {"name":"Cairns","lat":-16.92,"lon":145.77,"temp":31,"code":80,"precip":6.0,"snow":0,"wind":14,"icon":"\ud83c\udf27\ufe0f"}
      ],
      "Western Australia": [
        {"name":"Perth","lat":-31.95,"lon":115.86,"temp":25,"code":0,"precip":0,"snow":0,"wind":22,"icon":"\u2600\ufe0f"},
        {"name":"Fremantle","lat":-32.05,"lon":115.74,"temp":24,"code":0,"precip":0,"snow":0,"wind":24,"icon":"\u2600\ufe0f"},
        {"name":"Geraldton","lat":-28.78,"lon":114.61,"temp":26,"code":0,"precip":0,"snow":0,"wind":28,"icon":"\u2600\ufe0f"}
      ]
    },
    "JP": {
      "Tokyo": [
        {"name":"Tokyo","lat":35.68,"lon":139.69,"temp":18,"code":1,"precip":0,"snow":0,"wind":16,"icon":"\u26c5"},
        {"name":"Yokohama","lat":35.44,"lon":139.64,"temp":18,"code":1,"precip":0,"snow":0,"wind":18,"icon":"\u26c5"},
        {"name":"Kawasaki","lat":35.53,"lon":139.70,"temp":18,"code":2,"precip":0,"snow":0,"wind":16,"icon":"\u26c5"}
      ],
      "Osaka": [
        {"name":"Osaka","lat":34.68,"lon":135.50,"temp":19,"code":1,"precip":0,"snow":0,"wind":14,"icon":"\u26c5"},
        {"name":"Kyoto","lat":35.02,"lon":135.75,"temp":18,"code":1,"precip":0,"snow":0,"wind":12,"icon":"\u26c5"},
        {"name":"Kobe","lat":34.69,"lon":135.19,"temp":19,"code":0,"precip":0,"snow":0,"wind":16,"icon":"\u2600\ufe0f"}
      ],
      "Hokkaido": [
        {"name":"Sapporo","lat":43.06,"lon":141.35,"temp":5,"code":61,"precip":2.0,"snow":0,"wind":22,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Asahikawa","lat":43.77,"lon":142.38,"temp":3,"code":73,"precip":0,"snow":1.5,"wind":18,"icon":"\u2744\ufe0f"},
        {"name":"Hakodate","lat":41.77,"lon":140.73,"temp":8,"code":61,"precip":1.0,"snow":0,"wind":20,"icon":"\ud83c\udf27\ufe0f"}
      ],
      "Fukuoka": [
        {"name":"Fukuoka","lat":33.60,"lon":130.40,"temp":20,"code":0,"precip":0,"snow":0,"wind":14,"icon":"\u2600\ufe0f"},
        {"name":"Kitakyushu","lat":33.88,"lon":130.88,"temp":19,"code":1,"precip":0,"snow":0,"wind":16,"icon":"\u26c5"},
        {"name":"Kurume","lat":33.32,"lon":130.50,"temp":20,"code":0,"precip":0,"snow":0,"wind":12,"icon":"\u2600\ufe0f"}
      ]
    },
    "DE": {
      "Bavaria": [
        {"name":"Munich","lat":48.13,"lon":11.58,"temp":11,"code":2,"precip":0,"snow":0,"wind":18,"icon":"\u26c5"},
        {"name":"Nuremberg","lat":49.45,"lon":11.08,"temp":12,"code":2,"precip":0,"snow":0,"wind":20,"icon":"\u26c5"},
        {"name":"Augsburg","lat":48.37,"lon":10.90,"temp":11,"code":3,"precip":0,"snow":0,"wind":16,"icon":"\u2601\ufe0f"}
      ],
      "Berlin": [
        {"name":"Berlin","lat":52.52,"lon":13.41,"temp":14,"code":3,"precip":0,"snow":0,"wind":24,"icon":"\u2601\ufe0f"},
        {"name":"Potsdam","lat":52.39,"lon":13.06,"temp":13,"code":2,"precip":0,"snow":0,"wind":22,"icon":"\u26c5"},
        {"name":"Spandau","lat":52.54,"lon":13.20,"temp":14,"code":3,"precip":0,"snow":0,"wind":24,"icon":"\u2601\ufe0f"}
      ],
      "NRW": [
        {"name":"Cologne","lat":50.94,"lon":6.96,"temp":13,"code":61,"precip":1.2,"snow":0,"wind":28,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Dusseldorf","lat":51.22,"lon":6.78,"temp":13,"code":61,"precip":1.0,"snow":0,"wind":30,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Dortmund","lat":51.51,"lon":7.46,"temp":12,"code":61,"precip":0.8,"snow":0,"wind":32,"icon":"\ud83c\udf27\ufe0f"}
      ]
    },
    "FR": {
      "Ile-de-France": [
        {"name":"Paris","lat":48.86,"lon":2.35,"temp":15,"code":2,"precip":0,"snow":0,"wind":20,"icon":"\u26c5"},
        {"name":"Versailles","lat":48.80,"lon":2.13,"temp":14,"code":2,"precip":0,"snow":0,"wind":18,"icon":"\u26c5"},
        {"name":"Boulogne","lat":48.83,"lon":2.24,"temp":15,"code":1,"precip":0,"snow":0,"wind":22,"icon":"\u26c5"}
      ],
      "Provence": [
        {"name":"Marseille","lat":43.30,"lon":5.37,"temp":20,"code":0,"precip":0,"snow":0,"wind":30,"icon":"\u2600\ufe0f"},
        {"name":"Nice","lat":43.70,"lon":7.27,"temp":21,"code":0,"precip":0,"snow":0,"wind":18,"icon":"\u2600\ufe0f"},
        {"name":"Toulon","lat":43.12,"lon":5.93,"temp":19,"code":0,"precip":0,"snow":0,"wind":22,"icon":"\u2600\ufe0f"}
      ],
      "Auvergne": [
        {"name":"Lyon","lat":45.75,"lon":4.84,"temp":15,"code":1,"precip":0,"snow":0,"wind":16,"icon":"\u26c5"},
        {"name":"Grenoble","lat":45.19,"lon":5.72,"temp":13,"code":2,"precip":0,"snow":0,"wind":18,"icon":"\u26c5"},
        {"name":"Clermont","lat":45.78,"lon":3.08,"temp":14,"code":1,"precip":0,"snow":0,"wind":14,"icon":"\u26c5"}
      ]
    },
    "CN": {
      "Beijing": [
        {"name":"Beijing","lat":39.91,"lon":116.39,"temp":18,"code":2,"precip":0,"snow":0,"wind":20,"icon":"\u26c5"},
        {"name":"Tianjin","lat":39.13,"lon":117.20,"temp":18,"code":2,"precip":0,"snow":0,"wind":22,"icon":"\u26c5"},
        {"name":"Baoding","lat":38.87,"lon":115.46,"temp":17,"code":1,"precip":0,"snow":0,"wind":18,"icon":"\u26c5"}
      ],
      "Shanghai": [
        {"name":"Shanghai","lat":31.23,"lon":121.47,"temp":20,"code":1,"precip":0,"snow":0,"wind":16,"icon":"\u26c5"},
        {"name":"Suzhou","lat":31.30,"lon":120.62,"temp":20,"code":1,"precip":0,"snow":0,"wind":14,"icon":"\u26c5"},
        {"name":"Nanjing","lat":32.06,"lon":118.79,"temp":19,"code":2,"precip":0,"snow":0,"wind":18,"icon":"\u26c5"}
      ],
      "Guangdong": [
        {"name":"Guangzhou","lat":23.12,"lon":113.26,"temp":28,"code":80,"precip":5.0,"snow":0,"wind":18,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Shenzhen","lat":22.55,"lon":114.06,"temp":28,"code":80,"precip":4.5,"snow":0,"wind":16,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Zhuhai","lat":22.27,"lon":113.57,"temp":27,"code":80,"precip":3.5,"snow":0,"wind":20,"icon":"\ud83c\udf27\ufe0f"}
      ],
      "Sichuan": [
        {"name":"Chengdu","lat":30.67,"lon":104.07,"temp":18,"code":2,"precip":0,"snow":0,"wind":10,"icon":"\u26c5"},
        {"name":"Chongqing","lat":29.56,"lon":106.55,"temp":20,"code":3,"precip":0,"snow":0,"wind":12,"icon":"\u2601\ufe0f"},
        {"name":"Mianyang","lat":31.47,"lon":104.74,"temp":16,"code":2,"precip":0,"snow":0,"wind":14,"icon":"\u26c5"}
      ]
    },
    "BR": {
      "Sao Paulo": [
        {"name":"Sao Paulo","lat":-23.55,"lon":-46.63,"temp":23,"code":80,"precip":5.5,"snow":0,"wind":16,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Campinas","lat":-22.91,"lon":-47.06,"temp":25,"code":80,"precip":4.0,"snow":0,"wind":14,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Santos","lat":-23.96,"lon":-46.33,"temp":26,"code":80,"precip":6.0,"snow":0,"wind":18,"icon":"\ud83c\udf27\ufe0f"}
      ],
      "Rio de Janeiro": [
        {"name":"Rio de Janeiro","lat":-22.91,"lon":-43.17,"temp":30,"code":1,"precip":0,"snow":0,"wind":20,"icon":"\u26c5"},
        {"name":"Niteroi","lat":-22.89,"lon":-43.10,"temp":30,"code":1,"precip":0,"snow":0,"wind":18,"icon":"\u26c5"},
        {"name":"Nova Iguacu","lat":-22.76,"lon":-43.46,"temp":31,"code":0,"precip":0,"snow":0,"wind":16,"icon":"\u2600\ufe0f"}
      ],
      "Amazonas": [
        {"name":"Manaus","lat":-3.10,"lon":-60.03,"temp":33,"code":80,"precip":9.0,"snow":0,"wind":10,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Parintins","lat":-2.63,"lon":-56.74,"temp":32,"code":80,"precip":7.0,"snow":0,"wind":12,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Itacoatiara","lat":-3.14,"lon":-58.44,"temp":32,"code":80,"precip":8.0,"snow":0,"wind":10,"icon":"\ud83c\udf27\ufe0f"}
      ],
      "Bahia": [
        {"name":"Salvador","lat":-12.97,"lon":-38.50,"temp":30,"code":80,"precip":3.0,"snow":0,"wind":20,"icon":"\ud83c\udf27\ufe0f"},
        {"name":"Feira de Santana","lat":-12.27,"lon":-38.97,"temp":31,"code":0,"precip":0,"snow":0,"wind":18,"icon":"\u2600\ufe0f"},
        {"name":"Vitoria da Conquista","lat":-14.87,"lon":-40.84,"temp":24,"code":80,"precip":2.0,"snow":0,"wind":16,"icon":"\ud83c\udf27\ufe0f"}
      ]
    }
  }
};
