// Auto-generated by Playmix fetch_weather.py — 2026-05-04T05:37:52Z
// Do not edit manually. Run scripts/fetch_weather.py to refresh.
window.WEATHER_DATA = {
  "generated_at": "2026-05-04T05:37:52Z",
  "countries": {
    "IN": {
      "name": "India",
      "code": 0,
      "lat": 20.59,
      "lon": 78.96,
      "flag": "🇮🇳",
      "temp": 39,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 3,
      "icon": "☀️",
      "zoom": 5
    },
    "US": {
      "name": "USA",
      "code": 2,
      "lat": 37.09,
      "lon": -95.71,
      "flag": "🇺🇸",
      "temp": 19,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 26,
      "icon": "⛅",
      "zoom": 5
    },
    "BR": {
      "name": "Brazil",
      "code": 1,
      "lat": -14.23,
      "lon": -51.93,
      "flag": "🇧🇷",
      "temp": 24,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 2,
      "icon": "⛅",
      "zoom": 5
    },
    "CN": {
      "name": "China",
      "code": 0,
      "lat": 35.86,
      "lon": 104.19,
      "flag": "🇨🇳",
      "temp": 24,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 6,
      "icon": "☀️",
      "zoom": 5
    },
    "RU": {
      "name": "Russia",
      "code": 3,
      "lat": 61.52,
      "lon": 105.32,
      "flag": "🇷🇺",
      "temp": 2,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 17,
      "icon": "☁️",
      "zoom": 5
    },
    "AU": {
      "name": "Australia",
      "code": 0,
      "lat": -25.27,
      "lon": 133.78,
      "flag": "🇦🇺",
      "temp": 21,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 11,
      "icon": "☀️",
      "zoom": 5
    },
    "DE": {
      "name": "Germany",
      "code": 3,
      "lat": 51.17,
      "lon": 10.45,
      "flag": "🇩🇪",
      "temp": 13,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 2,
      "icon": "☁️",
      "zoom": 5
    },
    "FR": {
      "name": "France",
      "code": 80,
      "lat": 46.23,
      "lon": 2.21,
      "flag": "🇫🇷",
      "temp": 12,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 4,
      "icon": "🌧️",
      "zoom": 5
    },
    "JP": {
      "name": "Japan",
      "code": 1,
      "lat": 36.2,
      "lon": 138.25,
      "flag": "🇯🇵",
      "temp": 17,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 14,
      "icon": "⛅",
      "zoom": 5
    },
    "GB": {
      "name": "UK",
      "code": 3,
      "lat": 55.38,
      "lon": -3.44,
      "flag": "🇬🇧",
      "temp": 6,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 3,
      "icon": "☁️",
      "zoom": 5
    },
    "CA": {
      "name": "Canada",
      "code": 3,
      "lat": 56.13,
      "lon": -106.35,
      "flag": "🇨🇦",
      "temp": -1,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 15,
      "icon": "☁️",
      "zoom": 5
    },
    "MX": {
      "name": "Mexico",
      "code": 1,
      "lat": 23.63,
      "lon": -102.55,
      "flag": "🇲🇽",
      "temp": 19,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 26,
      "icon": "⛅",
      "zoom": 5
    },
    "ZA": {
      "name": "South Africa",
      "code": 2,
      "lat": -30.56,
      "lon": 22.94,
      "flag": "🇿🇦",
      "temp": 11,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 10,
      "icon": "⛅",
      "zoom": 5
    },
    "EG": {
      "name": "Egypt",
      "code": 0,
      "lat": 26.82,
      "lon": 30.8,
      "flag": "🇪🇬",
      "temp": 16,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 24,
      "icon": "☀️",
      "zoom": 5
    },
    "NG": {
      "name": "Nigeria",
      "code": 3,
      "lat": 9.08,
      "lon": 8.68,
      "flag": "🇳🇬",
      "temp": 24,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 4,
      "icon": "☁️",
      "zoom": 5
    },
    "ID": {
      "name": "Indonesia",
      "code": 3,
      "lat": -0.79,
      "lon": 113.92,
      "flag": "🇮🇩",
      "temp": 31,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 3,
      "icon": "☁️",
      "zoom": 5
    },
    "AR": {
      "name": "Argentina",
      "code": 0,
      "lat": -38.42,
      "lon": -63.62,
      "flag": "🇦🇷",
      "temp": 11,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 16,
      "icon": "☀️",
      "zoom": 5
    },
    "SA": {
      "name": "Saudi Arabia",
      "code": 0,
      "lat": 23.886,
      "lon": 45.08,
      "flag": "🇸🇦",
      "temp": 32,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 11,
      "icon": "☀️",
      "zoom": 5
    },
    "TR": {
      "name": "Turkey",
      "code": 3,
      "lat": 38.96,
      "lon": 35.24,
      "flag": "🇹🇷",
      "temp": 6,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 3,
      "icon": "☁️",
      "zoom": 5
    },
    "IT": {
      "name": "Italy",
      "code": 2,
      "lat": 41.87,
      "lon": 12.57,
      "flag": "🇮🇹",
      "temp": 11,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 2,
      "icon": "⛅",
      "zoom": 5
    },
    "ES": {
      "name": "Spain",
      "code": 2,
      "lat": 40.46,
      "lon": -3.75,
      "flag": "🇪🇸",
      "temp": 11,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 3,
      "icon": "⛅",
      "zoom": 5
    },
    "KR": {
      "name": "South Korea",
      "code": 0,
      "lat": 35.91,
      "lon": 127.77,
      "flag": "🇰🇷",
      "temp": 14,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 18,
      "icon": "☀️",
      "zoom": 5
    },
    "PK": {
      "name": "Pakistan",
      "code": 0,
      "lat": 30.38,
      "lon": 69.35,
      "flag": "🇵🇰",
      "temp": 27,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 8,
      "icon": "☀️",
      "zoom": 5
    },
    "BD": {
      "name": "Bangladesh",
      "code": 53,
      "lat": 23.68,
      "lon": 90.36,
      "flag": "🇧🇩",
      "temp": 27,
      "precip": 0.2,
      "snow": 0.0,
      "wind": 3,
      "icon": "🌧️",
      "zoom": 5
    },
    "VN": {
      "name": "Vietnam",
      "code": 3,
      "lat": 14.06,
      "lon": 108.28,
      "flag": "🇻🇳",
      "temp": 29,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 14,
      "icon": "☁️",
      "zoom": 5
    },
    "TH": {
      "name": "Thailand",
      "code": 1,
      "lat": 15.87,
      "lon": 100.99,
      "flag": "🇹🇭",
      "temp": 34,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 10,
      "icon": "⛅",
      "zoom": 5
    },
    "NL": {
      "name": "Netherlands",
      "code": 45,
      "lat": 52.13,
      "lon": 5.29,
      "flag": "🇳🇱",
      "temp": 11,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 2,
      "icon": "🌫️",
      "zoom": 5
    },
    "UA": {
      "name": "Ukraine",
      "code": 0,
      "lat": 48.38,
      "lon": 31.17,
      "flag": "🇺🇦",
      "temp": 12,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 5,
      "icon": "☀️",
      "zoom": 5
    },
    "PL": {
      "name": "Poland",
      "code": 3,
      "lat": 51.92,
      "lon": 19.14,
      "flag": "🇵🇱",
      "temp": 13,
      "precip": 0.0,
      "snow": 0.0,
      "wind": 16,
      "icon": "☁️",
      "zoom": 5
    },
    "SE": {
      "name": "Sweden",
      "code": 51,
      "lat": 60.13,
      "lon": 18.64,
      "flag": "🇸🇪",
      "temp": 6,
      "precip": 0.1,
      "snow": 0.0,
      "wind": 5,
      "icon": "🌧️",
      "zoom": 5
    }
  },
  "states": {
    "IN": [
      {
        "name": "Maharashtra",
        "lat": 19.75,
        "lon": 75.71,
        "temp": 35,
        "code": 0,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 12,
        "icon": "☀️"
      },
      {
        "name": "Delhi",
        "lat": 28.7,
        "lon": 77.1,
        "temp": 29,
        "code": 1,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 17,
        "icon": "⛅"
      },
      {
        "name": "Karnataka",
        "lat": 15.32,
        "lon": 75.71,
        "temp": 34,
        "code": 0,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 10,
        "icon": "☀️"
      },
      {
        "name": "Tamil Nadu",
        "lat": 11.13,
        "lon": 78.66,
        "temp": 36,
        "code": 3,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 7,
        "icon": "☁️"
      },
      {
        "name": "West Bengal",
        "lat": 22.99,
        "lon": 87.85,
        "temp": 29,
        "code": 51,
        "precip": 0.1,
        "snow": 0.0,
        "wind": 6,
        "icon": "🌧️"
      },
      {
        "name": "Gujarat",
        "lat": 22.26,
        "lon": 71.19,
        "temp": 35,
        "code": 0,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 14,
        "icon": "☀️"
      },
      {
        "name": "Rajasthan",
        "lat": 27.02,
        "lon": 74.22,
        "temp": 35,
        "code": 0,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 12,
        "icon": "☀️"
      },
      {
        "name": "Uttar Pradesh",
        "lat": 26.85,
        "lon": 80.91,
        "temp": 24,
        "code": 80,
        "precip": 0.6,
        "snow": 0.0,
        "wind": 17,
        "icon": "🌧️"
      }
    ],
    "US": [
      {
        "name": "California",
        "lat": 36.78,
        "lon": -119.42,
        "temp": 16,
        "code": 0,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 16,
        "icon": "☀️"
      },
      {
        "name": "Texas",
        "lat": 31.97,
        "lon": -99.9,
        "temp": 16,
        "code": 2,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 13,
        "icon": "⛅"
      },
      {
        "name": "New York",
        "lat": 42.17,
        "lon": -74.95,
        "temp": 5,
        "code": 0,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 11,
        "icon": "☀️"
      },
      {
        "name": "Florida",
        "lat": 27.99,
        "lon": -81.76,
        "temp": 19,
        "code": 2,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 11,
        "icon": "⛅"
      },
      {
        "name": "Illinois",
        "lat": 40.35,
        "lon": -88.99,
        "temp": 11,
        "code": 0,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 12,
        "icon": "☀️"
      },
      {
        "name": "Washington",
        "lat": 47.75,
        "lon": -120.74,
        "temp": 17,
        "code": 0,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 6,
        "icon": "☀️"
      }
    ],
    "GB": [
      {
        "name": "England",
        "lat": 52.35,
        "lon": -1.17,
        "temp": 10,
        "code": 3,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 9,
        "icon": "☁️"
      },
      {
        "name": "Scotland",
        "lat": 56.49,
        "lon": -4.2,
        "temp": 8,
        "code": 3,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 10,
        "icon": "☁️"
      },
      {
        "name": "Wales",
        "lat": 52.13,
        "lon": -3.78,
        "temp": 9,
        "code": 3,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 5,
        "icon": "☁️"
      }
    ],
    "AU": [
      {
        "name": "New South Wales",
        "lat": -32.16,
        "lon": 147.02,
        "temp": 19,
        "code": 0,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 10,
        "icon": "☀️"
      },
      {
        "name": "Victoria",
        "lat": -36.85,
        "lon": 144.28,
        "temp": 15,
        "code": 51,
        "precip": 0.1,
        "snow": 0.0,
        "wind": 25,
        "icon": "🌧️"
      },
      {
        "name": "Queensland",
        "lat": -22.57,
        "lon": 144.08,
        "temp": 28,
        "code": 0,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 10,
        "icon": "☀️"
      },
      {
        "name": "Western Australia",
        "lat": -25.33,
        "lon": 122.03,
        "temp": 21,
        "code": 0,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 18,
        "icon": "☀️"
      }
    ],
    "JP": [
      {
        "name": "Tokyo",
        "lat": 35.69,
        "lon": 139.69,
        "temp": 24,
        "code": 3,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 14,
        "icon": "☁️"
      },
      {
        "name": "Osaka",
        "lat": 34.67,
        "lon": 135.5,
        "temp": 19,
        "code": 1,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 17,
        "icon": "⛅"
      },
      {
        "name": "Hokkaido",
        "lat": 43.46,
        "lon": 142.83,
        "temp": 4,
        "code": 55,
        "precip": 0.3,
        "snow": 0.0,
        "wind": 5,
        "icon": "🌧️"
      },
      {
        "name": "Fukuoka",
        "lat": 33.56,
        "lon": 130.72,
        "temp": 18,
        "code": 1,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 14,
        "icon": "⛅"
      }
    ],
    "DE": [
      {
        "name": "Bavaria",
        "lat": 48.79,
        "lon": 11.5,
        "temp": 12,
        "code": 2,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 5,
        "icon": "⛅"
      },
      {
        "name": "Berlin",
        "lat": 52.52,
        "lon": 13.4,
        "temp": 17,
        "code": 2,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 7,
        "icon": "⛅"
      },
      {
        "name": "NRW",
        "lat": 51.43,
        "lon": 7.66,
        "temp": 13,
        "code": 3,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 2,
        "icon": "☁️"
      }
    ],
    "FR": [
      {
        "name": "Île-de-France",
        "lat": 48.85,
        "lon": 2.35,
        "temp": 14,
        "code": 61,
        "precip": 0.1,
        "snow": 0.0,
        "wind": 1,
        "icon": "🌧️"
      },
      {
        "name": "Provence",
        "lat": 43.83,
        "lon": 5.71,
        "temp": 11,
        "code": 61,
        "precip": 0.6,
        "snow": 0.0,
        "wind": 9,
        "icon": "🌧️"
      },
      {
        "name": "Auvergne",
        "lat": 45.75,
        "lon": 3.07,
        "temp": 10,
        "code": 61,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 2,
        "icon": "🌧️"
      }
    ],
    "CN": [
      {
        "name": "Beijing",
        "lat": 39.91,
        "lon": 116.39,
        "temp": 24,
        "code": 0,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 15,
        "icon": "☀️"
      },
      {
        "name": "Shanghai",
        "lat": 31.23,
        "lon": 121.47,
        "temp": 23,
        "code": 3,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 6,
        "icon": "☁️"
      },
      {
        "name": "Guangdong",
        "lat": 23.37,
        "lon": 113.5,
        "temp": 24,
        "code": 3,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 5,
        "icon": "☁️"
      },
      {
        "name": "Sichuan",
        "lat": 30.65,
        "lon": 102.71,
        "temp": 8,
        "code": 1,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 6,
        "icon": "⛅"
      }
    ],
    "BR": [
      {
        "name": "São Paulo",
        "lat": -23.55,
        "lon": -46.63,
        "temp": 14,
        "code": 2,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 10,
        "icon": "⛅"
      },
      {
        "name": "Rio de Janeiro",
        "lat": -22.91,
        "lon": -43.17,
        "temp": 22,
        "code": 3,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 6,
        "icon": "☁️"
      },
      {
        "name": "Amazonas",
        "lat": -3.07,
        "lon": -60.01,
        "temp": 24,
        "code": 53,
        "precip": 0.2,
        "snow": 0.0,
        "wind": 1,
        "icon": "🌧️"
      },
      {
        "name": "Bahia",
        "lat": -12.97,
        "lon": -38.51,
        "temp": 26,
        "code": 2,
        "precip": 0.0,
        "snow": 0.0,
        "wind": 17,
        "icon": "⛅"
      }
    ]
  },
  "cities": {
    "IN": {
      "Maharashtra": [
        {
          "name": "Mumbai",
          "lat": 19.07,
          "lon": 72.87,
          "temp": 32,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 13,
          "icon": "☀️"
        },
        {
          "name": "Pune",
          "lat": 18.52,
          "lon": 73.85,
          "temp": 33,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 15,
          "icon": "☀️"
        },
        {
          "name": "Nagpur",
          "lat": 21.14,
          "lon": 79.09,
          "temp": 39,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 3,
          "icon": "☀️"
        }
      ],
      "Delhi": [
        {
          "name": "New Delhi",
          "lat": 28.61,
          "lon": 77.21,
          "temp": 29,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 17,
          "icon": "☀️"
        },
        {
          "name": "Noida",
          "lat": 28.54,
          "lon": 77.39,
          "temp": 30,
          "code": 1,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 17,
          "icon": "⛅"
        },
        {
          "name": "Gurgaon",
          "lat": 28.45,
          "lon": 77.03,
          "temp": 30,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 20,
          "icon": "☀️"
        }
      ],
      "Karnataka": [
        {
          "name": "Bengaluru",
          "lat": 12.97,
          "lon": 77.59,
          "temp": 32,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 10,
          "icon": "⛅"
        },
        {
          "name": "Mysuru",
          "lat": 12.3,
          "lon": 76.65,
          "temp": 31,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 5,
          "icon": "⛅"
        },
        {
          "name": "Hubli",
          "lat": 15.36,
          "lon": 75.12,
          "temp": 33,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 11,
          "icon": "☀️"
        }
      ],
      "Tamil Nadu": [
        {
          "name": "Chennai",
          "lat": 13.08,
          "lon": 80.28,
          "temp": 34,
          "code": 95,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 14,
          "icon": "⛈️"
        },
        {
          "name": "Coimbatore",
          "lat": 11.02,
          "lon": 76.96,
          "temp": 34,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 7,
          "icon": "☁️"
        },
        {
          "name": "Madurai",
          "lat": 9.93,
          "lon": 78.12,
          "temp": 38,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 2,
          "icon": "☁️"
        }
      ],
      "West Bengal": [
        {
          "name": "Kolkata",
          "lat": 22.57,
          "lon": 88.36,
          "temp": 31,
          "code": 1,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 3,
          "icon": "⛅"
        },
        {
          "name": "Howrah",
          "lat": 22.59,
          "lon": 88.31,
          "temp": 31,
          "code": 1,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 3,
          "icon": "⛅"
        },
        {
          "name": "Darjeeling",
          "lat": 27.04,
          "lon": 88.27,
          "temp": 17,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 5,
          "icon": "⛅"
        }
      ],
      "Gujarat": [
        {
          "name": "Ahmedabad",
          "lat": 23.02,
          "lon": 72.57,
          "temp": 34,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 9,
          "icon": "☀️"
        },
        {
          "name": "Surat",
          "lat": 21.17,
          "lon": 72.83,
          "temp": 34,
          "code": 1,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 18,
          "icon": "⛅"
        },
        {
          "name": "Vadodara",
          "lat": 22.31,
          "lon": 73.18,
          "temp": 35,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 13,
          "icon": "☀️"
        }
      ],
      "Rajasthan": [
        {
          "name": "Jaipur",
          "lat": 26.91,
          "lon": 75.79,
          "temp": 32,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 13,
          "icon": "☀️"
        },
        {
          "name": "Jodhpur",
          "lat": 26.29,
          "lon": 73.02,
          "temp": 36,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 12,
          "icon": "☀️"
        },
        {
          "name": "Udaipur",
          "lat": 24.58,
          "lon": 73.68,
          "temp": 33,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 12,
          "icon": "☀️"
        }
      ],
      "Uttar Pradesh": [
        {
          "name": "Lucknow",
          "lat": 26.85,
          "lon": 80.95,
          "temp": 24,
          "code": 80,
          "precip": 0.6,
          "snow": 0.0,
          "wind": 17,
          "icon": "🌧️"
        },
        {
          "name": "Kanpur",
          "lat": 26.47,
          "lon": 80.33,
          "temp": 27,
          "code": 51,
          "precip": 0.1,
          "snow": 0.0,
          "wind": 14,
          "icon": "🌧️"
        },
        {
          "name": "Varanasi",
          "lat": 25.32,
          "lon": 83.01,
          "temp": 34,
          "code": 1,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 16,
          "icon": "⛅"
        }
      ]
    },
    "US": {
      "California": [
        {
          "name": "Los Angeles",
          "lat": 34.05,
          "lon": -118.24,
          "temp": 14,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 2,
          "icon": "☁️"
        },
        {
          "name": "San Francisco",
          "lat": 37.77,
          "lon": -122.42,
          "temp": 12,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 12,
          "icon": "☀️"
        },
        {
          "name": "San Diego",
          "lat": 32.72,
          "lon": -117.15,
          "temp": 17,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 4,
          "icon": "☁️"
        }
      ],
      "Texas": [
        {
          "name": "Houston",
          "lat": 29.76,
          "lon": -95.37,
          "temp": 16,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 9,
          "icon": "⛅"
        },
        {
          "name": "Dallas",
          "lat": 32.78,
          "lon": -96.8,
          "temp": 19,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 13,
          "icon": "☀️"
        },
        {
          "name": "Austin",
          "lat": 30.27,
          "lon": -97.74,
          "temp": 18,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 5,
          "icon": "☁️"
        }
      ],
      "New York": [
        {
          "name": "New York City",
          "lat": 40.71,
          "lon": -74.01,
          "temp": 9,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 17,
          "icon": "☀️"
        },
        {
          "name": "Buffalo",
          "lat": 42.89,
          "lon": -78.86,
          "temp": 10,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 26,
          "icon": "☀️"
        },
        {
          "name": "Albany",
          "lat": 42.65,
          "lon": -73.76,
          "temp": 7,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 8,
          "icon": "⛅"
        }
      ],
      "Florida": [
        {
          "name": "Miami",
          "lat": 25.78,
          "lon": -80.21,
          "temp": 23,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 5,
          "icon": "☁️"
        },
        {
          "name": "Orlando",
          "lat": 28.54,
          "lon": -81.38,
          "temp": 19,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 5,
          "icon": "☁️"
        },
        {
          "name": "Tampa",
          "lat": 27.95,
          "lon": -82.46,
          "temp": 20,
          "code": 1,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 8,
          "icon": "⛅"
        }
      ],
      "Illinois": [
        {
          "name": "Chicago",
          "lat": 41.85,
          "lon": -87.65,
          "temp": 12,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 11,
          "icon": "☀️"
        },
        {
          "name": "Springfield",
          "lat": 39.78,
          "lon": -89.65,
          "temp": 15,
          "code": 1,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 6,
          "icon": "⛅"
        },
        {
          "name": "Rockford",
          "lat": 42.27,
          "lon": -89.09,
          "temp": 11,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 7,
          "icon": "☀️"
        }
      ],
      "Washington": [
        {
          "name": "Seattle",
          "lat": 47.61,
          "lon": -122.33,
          "temp": 18,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 6,
          "icon": "☀️"
        },
        {
          "name": "Spokane",
          "lat": 47.66,
          "lon": -117.43,
          "temp": 18,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 5,
          "icon": "☀️"
        },
        {
          "name": "Tacoma",
          "lat": 47.25,
          "lon": -122.44,
          "temp": 19,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 7,
          "icon": "☀️"
        }
      ]
    },
    "GB": {
      "England": [
        {
          "name": "London",
          "lat": 51.5,
          "lon": -0.12,
          "temp": 13,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 8,
          "icon": "☁️"
        },
        {
          "name": "Manchester",
          "lat": 53.48,
          "lon": -2.24,
          "temp": 9,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 8,
          "icon": "☁️"
        },
        {
          "name": "Birmingham",
          "lat": 52.48,
          "lon": -1.9,
          "temp": 10,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 9,
          "icon": "☁️"
        }
      ],
      "Scotland": [
        {
          "name": "Edinburgh",
          "lat": 55.95,
          "lon": -3.19,
          "temp": 8,
          "code": 51,
          "precip": 0.1,
          "snow": 0.0,
          "wind": 7,
          "icon": "🌧️"
        },
        {
          "name": "Glasgow",
          "lat": 55.86,
          "lon": -4.25,
          "temp": 9,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 8,
          "icon": "☁️"
        },
        {
          "name": "Aberdeen",
          "lat": 57.15,
          "lon": -2.11,
          "temp": 7,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 6,
          "icon": "☁️"
        }
      ],
      "Wales": [
        {
          "name": "Cardiff",
          "lat": 51.48,
          "lon": -3.18,
          "temp": 12,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 12,
          "icon": "☁️"
        },
        {
          "name": "Swansea",
          "lat": 51.62,
          "lon": -3.94,
          "temp": 12,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 9,
          "icon": "☁️"
        },
        {
          "name": "Newport",
          "lat": 51.59,
          "lon": -2.99,
          "temp": 12,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 12,
          "icon": "☁️"
        }
      ]
    },
    "AU": {
      "New South Wales": [
        {
          "name": "Sydney",
          "lat": -33.87,
          "lon": 151.21,
          "temp": 22,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 13,
          "icon": "☁️"
        },
        {
          "name": "Newcastle",
          "lat": -32.93,
          "lon": 151.78,
          "temp": 25,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 6,
          "icon": "☁️"
        },
        {
          "name": "Wollongong",
          "lat": -34.42,
          "lon": 150.89,
          "temp": 21,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 15,
          "icon": "⛅"
        }
      ],
      "Victoria": [
        {
          "name": "Melbourne",
          "lat": -37.81,
          "lon": 144.96,
          "temp": 18,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 25,
          "icon": "⛅"
        },
        {
          "name": "Geelong",
          "lat": -38.15,
          "lon": 144.36,
          "temp": 18,
          "code": 1,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 26,
          "icon": "⛅"
        },
        {
          "name": "Ballarat",
          "lat": -37.56,
          "lon": 143.87,
          "temp": 12,
          "code": 51,
          "precip": 0.1,
          "snow": 0.0,
          "wind": 28,
          "icon": "🌧️"
        }
      ],
      "Queensland": [
        {
          "name": "Brisbane",
          "lat": -27.47,
          "lon": 153.02,
          "temp": 24,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 9,
          "icon": "☀️"
        },
        {
          "name": "Gold Coast",
          "lat": -28.02,
          "lon": 153.4,
          "temp": 23,
          "code": 1,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 11,
          "icon": "⛅"
        },
        {
          "name": "Cairns",
          "lat": -16.92,
          "lon": 145.77,
          "temp": 26,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 13,
          "icon": "☁️"
        }
      ],
      "Western Australia": [
        {
          "name": "Perth",
          "lat": -31.95,
          "lon": 115.86,
          "temp": 20,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 4,
          "icon": "☀️"
        },
        {
          "name": "Fremantle",
          "lat": -32.05,
          "lon": 115.74,
          "temp": 20,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 1,
          "icon": "☀️"
        },
        {
          "name": "Geraldton",
          "lat": -28.78,
          "lon": 114.61,
          "temp": 25,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 15,
          "icon": "☀️"
        }
      ]
    },
    "JP": {
      "Tokyo": [
        {
          "name": "Tokyo",
          "lat": 35.68,
          "lon": 139.69,
          "temp": 24,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 14,
          "icon": "☁️"
        },
        {
          "name": "Yokohama",
          "lat": 35.44,
          "lon": 139.64,
          "temp": 23,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 17,
          "icon": "⛅"
        },
        {
          "name": "Kawasaki",
          "lat": 35.53,
          "lon": 139.7,
          "temp": 23,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 17,
          "icon": "☁️"
        }
      ],
      "Osaka": [
        {
          "name": "Osaka",
          "lat": 34.68,
          "lon": 135.5,
          "temp": 20,
          "code": 1,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 18,
          "icon": "⛅"
        },
        {
          "name": "Kyoto",
          "lat": 35.02,
          "lon": 135.75,
          "temp": 21,
          "code": 1,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 12,
          "icon": "⛅"
        },
        {
          "name": "Kobe",
          "lat": 34.69,
          "lon": 135.19,
          "temp": 19,
          "code": 1,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 18,
          "icon": "⛅"
        }
      ],
      "Hokkaido": [
        {
          "name": "Sapporo",
          "lat": 43.06,
          "lon": 141.35,
          "temp": 14,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 2,
          "icon": "☁️"
        },
        {
          "name": "Asahikawa",
          "lat": 43.77,
          "lon": 142.38,
          "temp": 6,
          "code": 55,
          "precip": 0.3,
          "snow": 0.0,
          "wind": 8,
          "icon": "🌧️"
        },
        {
          "name": "Hakodate",
          "lat": 41.77,
          "lon": 140.73,
          "temp": 12,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 36,
          "icon": "⛅"
        }
      ],
      "Fukuoka": [
        {
          "name": "Fukuoka",
          "lat": 33.6,
          "lon": 130.4,
          "temp": 17,
          "code": 1,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 23,
          "icon": "⛅"
        },
        {
          "name": "Kitakyushu",
          "lat": 33.88,
          "lon": 130.88,
          "temp": 17,
          "code": 1,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 20,
          "icon": "⛅"
        },
        {
          "name": "Kurume",
          "lat": 33.32,
          "lon": 130.5,
          "temp": 20,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 18,
          "icon": "⛅"
        }
      ]
    },
    "DE": {
      "Bavaria": [
        {
          "name": "Munich",
          "lat": 48.13,
          "lon": 11.58,
          "temp": 14,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 3,
          "icon": "☁️"
        },
        {
          "name": "Nuremberg",
          "lat": 49.45,
          "lon": 11.08,
          "temp": 14,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 4,
          "icon": "☁️"
        },
        {
          "name": "Augsburg",
          "lat": 48.37,
          "lon": 10.9,
          "temp": 13,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 4,
          "icon": "⛅"
        }
      ],
      "Berlin": [
        {
          "name": "Berlin",
          "lat": 52.52,
          "lon": 13.41,
          "temp": 17,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 7,
          "icon": "⛅"
        },
        {
          "name": "Potsdam",
          "lat": 52.39,
          "lon": 13.06,
          "temp": 16,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 6,
          "icon": "☁️"
        },
        {
          "name": "Spandau",
          "lat": 52.54,
          "lon": 13.2,
          "temp": 16,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 6,
          "icon": "☁️"
        }
      ],
      "NRW": [
        {
          "name": "Cologne",
          "lat": 50.94,
          "lon": 6.96,
          "temp": 14,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 8,
          "icon": "⛅"
        },
        {
          "name": "Düsseldorf",
          "lat": 51.22,
          "lon": 6.78,
          "temp": 14,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 7,
          "icon": "☀️"
        },
        {
          "name": "Dortmund",
          "lat": 51.51,
          "lon": 7.46,
          "temp": 15,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 7,
          "icon": "⛅"
        }
      ]
    },
    "FR": {
      "Île-de-France": [
        {
          "name": "Paris",
          "lat": 48.86,
          "lon": 2.35,
          "temp": 14,
          "code": 61,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 1,
          "icon": "🌧️"
        },
        {
          "name": "Versailles",
          "lat": 48.8,
          "lon": 2.13,
          "temp": 13,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 1,
          "icon": "☁️"
        },
        {
          "name": "Boulogne",
          "lat": 48.83,
          "lon": 2.24,
          "temp": 14,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 1,
          "icon": "☁️"
        }
      ],
      "Provence": [
        {
          "name": "Marseille",
          "lat": 43.3,
          "lon": 5.37,
          "temp": 16,
          "code": 3,
          "precip": 0.1,
          "snow": 0.0,
          "wind": 19,
          "icon": "☁️"
        },
        {
          "name": "Nice",
          "lat": 43.7,
          "lon": 7.27,
          "temp": 14,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 6,
          "icon": "☁️"
        },
        {
          "name": "Toulon",
          "lat": 43.12,
          "lon": 5.93,
          "temp": 16,
          "code": 3,
          "precip": 0.1,
          "snow": 0.0,
          "wind": 15,
          "icon": "☁️"
        }
      ],
      "Auvergne": [
        {
          "name": "Lyon",
          "lat": 45.75,
          "lon": 4.84,
          "temp": 14,
          "code": 61,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 4,
          "icon": "🌧️"
        },
        {
          "name": "Grenoble",
          "lat": 45.19,
          "lon": 5.72,
          "temp": 14,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 5,
          "icon": "☁️"
        },
        {
          "name": "Clermont",
          "lat": 45.78,
          "lon": 3.08,
          "temp": 12,
          "code": 61,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 1,
          "icon": "🌧️"
        }
      ]
    },
    "CN": {
      "Beijing": [
        {
          "name": "Beijing",
          "lat": 39.91,
          "lon": 116.39,
          "temp": 24,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 15,
          "icon": "☀️"
        },
        {
          "name": "Tianjin",
          "lat": 39.13,
          "lon": 117.2,
          "temp": 23,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 14,
          "icon": "☀️"
        },
        {
          "name": "Baoding",
          "lat": 38.87,
          "lon": 115.46,
          "temp": 23,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 16,
          "icon": "☀️"
        }
      ],
      "Shanghai": [
        {
          "name": "Shanghai",
          "lat": 31.23,
          "lon": 121.47,
          "temp": 23,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 6,
          "icon": "☁️"
        },
        {
          "name": "Suzhou",
          "lat": 31.3,
          "lon": 120.62,
          "temp": 23,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 7,
          "icon": "☁️"
        },
        {
          "name": "Nanjing",
          "lat": 32.06,
          "lon": 118.79,
          "temp": 25,
          "code": 1,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 9,
          "icon": "⛅"
        }
      ],
      "Guangdong": [
        {
          "name": "Guangzhou",
          "lat": 23.12,
          "lon": 113.26,
          "temp": 26,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 8,
          "icon": "☁️"
        },
        {
          "name": "Shenzhen",
          "lat": 22.55,
          "lon": 114.06,
          "temp": 25,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 8,
          "icon": "☁️"
        },
        {
          "name": "Zhuhai",
          "lat": 22.27,
          "lon": 113.57,
          "temp": 25,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 10,
          "icon": "☁️"
        }
      ],
      "Sichuan": [
        {
          "name": "Chengdu",
          "lat": 30.67,
          "lon": 104.07,
          "temp": 25,
          "code": 1,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 6,
          "icon": "⛅"
        },
        {
          "name": "Chongqing",
          "lat": 29.56,
          "lon": 106.55,
          "temp": 25,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 3,
          "icon": "☀️"
        },
        {
          "name": "Mianyang",
          "lat": 31.47,
          "lon": 104.74,
          "temp": 24,
          "code": 1,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 15,
          "icon": "⛅"
        }
      ]
    },
    "BR": {
      "São Paulo": [
        {
          "name": "São Paulo",
          "lat": -23.55,
          "lon": -46.63,
          "temp": 14,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 10,
          "icon": "⛅"
        },
        {
          "name": "Campinas",
          "lat": -22.91,
          "lon": -47.06,
          "temp": 16,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 18,
          "icon": "☀️"
        },
        {
          "name": "Santos",
          "lat": -23.96,
          "lon": -46.33,
          "temp": 19,
          "code": 0,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 7,
          "icon": "☀️"
        }
      ],
      "Rio de Janeiro": [
        {
          "name": "Rio de Janeiro",
          "lat": -22.91,
          "lon": -43.17,
          "temp": 22,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 6,
          "icon": "☁️"
        },
        {
          "name": "Niterói",
          "lat": -22.89,
          "lon": -43.1,
          "temp": 20,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 6,
          "icon": "☁️"
        },
        {
          "name": "Nova Iguaçu",
          "lat": -22.76,
          "lon": -43.46,
          "temp": 20,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 0,
          "icon": "⛅"
        }
      ],
      "Amazonas": [
        {
          "name": "Manaus",
          "lat": -3.1,
          "lon": -60.03,
          "temp": 25,
          "code": 53,
          "precip": 0.2,
          "snow": 0.0,
          "wind": 2,
          "icon": "🌧️"
        },
        {
          "name": "Parintins",
          "lat": -2.63,
          "lon": -56.74,
          "temp": 24,
          "code": 51,
          "precip": 0.1,
          "snow": 0.0,
          "wind": 7,
          "icon": "🌧️"
        },
        {
          "name": "Itacoatiara",
          "lat": -3.14,
          "lon": -58.44,
          "temp": 25,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 6,
          "icon": "☁️"
        }
      ],
      "Bahia": [
        {
          "name": "Salvador",
          "lat": -12.97,
          "lon": -38.5,
          "temp": 26,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 17,
          "icon": "⛅"
        },
        {
          "name": "Feira de Santana",
          "lat": -12.27,
          "lon": -38.97,
          "temp": 22,
          "code": 2,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 8,
          "icon": "⛅"
        },
        {
          "name": "Vitória da Conquista",
          "lat": -14.87,
          "lon": -40.84,
          "temp": 18,
          "code": 3,
          "precip": 0.0,
          "snow": 0.0,
          "wind": 21,
          "icon": "☁️"
        }
      ]
    }
  }
};
