// Auto-generated by fetch_news.py on 2026-04-18T10:50:29.261707Z
window.NEWS_DATA = {
    "top": [
        {
            "title": "Oil prices plunge as Iran says Strait of Hormuz 'open' during ceasefire",
            "link": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE5lcGI2VEVhSWFzLWZ1UExlN2JqWjBvQ3ZCLWc1WDBYNG5NMWFPZlZfT0hFcnNfVTF6dHk3NmtuSGQ0a19uVnRMSENZdk1vQ3h3REFKSFlaOXhpQQ?oc=5",
            "pubDate": "Sat, 18 Apr 2026 06:06:38 GMT",
            "source": "BBC"
        },
        {
            "title": "Iran disputes claims of new agreements with Trump",
            "link": "https://news.google.com/rss/articles/CBMiigFBVV95cUxOUlNlRHlIanI0Z0oyT3NPdkRSVXpwbmVCaXVKNGNKZE8wVEFOV0JvXzRScV9pRjZZNHJhOTN5R0JOYThKSG5VWGJVZl9FcE1ZSVhVamFZNFpzUE1BMVE3aF9XWXZzUHZHLXB4MENVZFRwTFhqTm5iRGNKVC1WSGozVGJ2VGNhOFB6ZXc?oc=5",
            "pubDate": "Sat, 18 Apr 2026 09:29:06 GMT",
            "source": "The Washington Post"
        },
        {
            "title": "Live updates: Life-threatening storms target the Heartland, intense tornadoes and huge hail possible",
            "link": "https://news.google.com/rss/articles/CBMi0AFBVV95cUxNRDZ5Z2dOWjd4U3FZZXRmQS10Y2RvMExOaWZMUjhNZnpGRURaRTZpTjRXOFB1S1E4aE9rSmxBTWQ4QVlnWWpnNUJXbHVoUGpXcFRqNk52OVJpb2t0TnVZaW5UUDNvcmN6VFV3bks5ZXljLXFaMGY2YmM4cTNseVpQaFJBbVp4Nk51aGZ1Q2RvZFZZdjYwaU9oa0syMmphSTZRdXZsSldwVEZBTktzR2gxWGxpdlJlUVgtQS1jNTBuelZsSlRwMV9QaFZiVWZqSkxp?oc=5",
            "pubDate": "Sat, 18 Apr 2026 03:55:15 GMT",
            "source": "FOX Weather"
        },
        {
            "title": "Trump suffers rare defeat with House Republicans on FISA",
            "link": "https://news.google.com/rss/articles/CBMiYEFVX3lxTE53eXk5VnBBQ1BKU2tGcjNVa2lFNTA5WEhZMXZHNzMxZ0t1SUVRb2RzQ05QcW5yeUd5eFprUllGWDF4M2tPeVlfOFZjZ2FSVVhNWXJ2Z19ZVWpNU0xXWVBUQw?oc=5",
            "pubDate": "Sat, 18 Apr 2026 03:39:42 GMT",
            "source": "Axios"
        },
        {
            "title": "EU officials in Hungary to discuss unlocking billions of euros held while Orb\u00e1n was in charge",
            "link": "https://news.google.com/rss/articles/CBMikwFBVV95cUxOTEttWHdvLXRIc3VZRk1zMHBxMEY2X0Yyd2tUWUdya2pPQTR6ZjVSam9HbUZIdHhYbl9Ba2JKQy1wSHI3b1AxSzJjVkxTalNfMjlscExCQnJnR0E3VEtXUEtMSmNRYXRBemkwamtPbFJkYnE4N1UyaUNNOWJjb1dGTHl6NGt3UkRpc25OVjNncXV2T3c?oc=5",
            "pubDate": "Fri, 17 Apr 2026 09:00:00 GMT",
            "source": "AP News"
        },
        {
            "title": "How the dispute between Trump and Pope Leo escalated",
            "link": "https://news.google.com/rss/articles/CBMidEFVX3lxTE1kOGU1NzhQaWZkMW5xdk40SHpzd3JLbzZHQm1JODllb0lVNGRCRkYzUnduMVplUXpEaVVBRDZMWUdINUZBS3ZaOUdWZV85UmtWZUxtWEZVODZkVDdaNGgtcGppX3RodjM4dDMwUm51cU9rMVdH0gF6QVVfeXFMTXF2ZkFMR0s1dUc5a09LQjROX0dfaDZoRGN5dU9lREM0OXNFYmtYQzVPQVNydWdXdFVNTzhPakhZSUlWNThDaVF3VFM3MUhBOWJHbWlOMHdnUllfX09ZOGxlZ1Z2VjhjSjAwMEpaQ1B6bTZPdjQzNFpiUHc?oc=5",
            "pubDate": "Sat, 18 Apr 2026 00:42:00 GMT",
            "source": "CBS News"
        },
        {
            "title": "Trump shocked Netanyahu with post declaring Lebanon strikes \"prohibited\"",
            "link": "https://news.google.com/rss/articles/CBMifEFVX3lxTE5EMU1xcVliYXFyNVF2QW00bnNUNmdCZm9vRWpLM1FhTkhuUVZTamVXd01nZVBERWx2TFNSR19RQVNCR2NJNU0tR0ZSSllXSjAwQXZaTVAtSHQwVHMwTzdqNUNpWWtiQlgzMU9KdlJkeEtuZDlNRmNZaTRaWmc?oc=5",
            "pubDate": "Fri, 17 Apr 2026 20:47:58 GMT",
            "source": "Axios"
        },
        {
            "title": "Trump to release reading of scripture days after angering many Christians",
            "link": "https://news.google.com/rss/articles/CBMijgFBVV95cUxNUjhpYlhBTEFwR3dOdHVSOFpadmY5R0MzRTRwYjRkSVlHdjczMmNPZ3I5SUxhbV95VUQzM09qY19GcGFXY2RtX0c3ckllSW51ckdZeUxTN0k2aTJjX0NHd20wcllFVDJ0RGdnRGtBbkRSLVA5akFobE02dHphMDdsVmwtN2NnZW4tdDNMWXpR?oc=5",
            "pubDate": "Sat, 18 Apr 2026 00:57:41 GMT",
            "source": "Politico"
        },
        {
            "title": "Mejia scored an NJ-11 landslide \u2013 but not everywhere",
            "link": "https://news.google.com/rss/articles/CBMikAFBVV95cUxPYUlTTFF5Z1FWemJYS3NxQi1JR2lZY1piTzJ5MjNZTEU5NWJyLU9vMnBzcHhEVEg5M08td3dIcHR4enlfdWRmc1pjaUM2ekNyV180el9VNGhxOTdYV3pIWFlIZTZFT09VeC1IZGpFc2h0QnExcy1aRkI3aFNPcnh6OGFWU2FhNmQ4bU5sbUxsNkg?oc=5",
            "pubDate": "Sat, 18 Apr 2026 01:13:04 GMT",
            "source": "New Jersey Globe"
        },
        {
            "title": "Trump came to Arizona to rally young voters. An older crowd greeted him.",
            "link": "https://news.google.com/rss/articles/CBMihgFBVV95cUxQMFRuYjZtZTg1N3Rpc0w0cVRMbXhYTTlnWDJfdEt6OWxoNHpmNE4wWmxydHlOalRXcndiVzh4TkpGak1nRThlcDBlZTZFREhLNmxYbXlOeWtadzd2bERYZXZXTnN4YXJBTXlXeXc1UTdhYjFvd3dCak5DeHZXQmJIbDZMZGFPZw?oc=5",
            "pubDate": "Sat, 18 Apr 2026 03:31:00 GMT",
            "source": "The Washington Post"
        },
        {
            "title": "'Staggering' I was not told Mandelson failed vetting, says PM",
            "link": "https://news.google.com/rss/articles/CBMiWkFVX3lxTFBnSDdhRHR2WWR4VHI0RHlxSFdjeFJoVXNmbXFWTWJYUnIybWNLV3BtbTR0T0JUMVhCdWQxczZsUVgtT2R5Z25CUk02aHItUi1XQmpLRVBFSm4xQQ?oc=5",
            "pubDate": "Sat, 18 Apr 2026 00:00:19 GMT",
            "source": "BBC"
        },
        {
            "title": "In Angola, Pope Leo XIV Faces the Legacy of Colonialism",
            "link": "https://news.google.com/rss/articles/CBMiiwFBVV95cUxNaXozbzVjQXVlc0dSMWpRQTVjUndvYkhXaV9jeU1Ka0NOdjZ2WTdDa1VYWF81VUFxbDFJMmc3Z0tZNUp6emJmNnROZlVlQWRrZFN4VzltX3NISUxtWkxSazVmXzRwTldWZmxnUHBRQlBWcGoxZFdUclhQVkhZMjlvamFvMm02RDdSYkkw?oc=5",
            "pubDate": "Sat, 18 Apr 2026 08:54:09 GMT",
            "source": "The New York Times"
        },
        {
            "title": "Maduro Is Gone, and the Purge Has Begun",
            "link": "https://news.google.com/rss/articles/CBMimgFBVV95cUxNTXNkcGxubklWVkNRdHJFcHNBNGRQYW5udTRlTE12ekpkMko1ckNKUlh1aU9GS19ReFFnNEt2WUE2a29MTWZrbEFNSG5nWHMyNnRLS0tYVE91U29Pb2xEWFIwV2ZJbkR4d0RiU2JnLVFiV2FRY1RzYWZoR3J5cGhQZFhtMnN5OXZRdC0tc1ZSR3VLUG8wYzJhRkVB?oc=5",
            "pubDate": "Sat, 18 Apr 2026 09:00:36 GMT",
            "source": "The New York Times"
        },
        {
            "title": "Japan seals largest-ever defense contract with frigate sale to Australia",
            "link": "https://news.google.com/rss/articles/CBMikAFBVV95cUxNTmZBOHhVMTRaaU1BLTAxcmQ1ejhSNl83OG95ZXRVMU9uODFNUWlmOXhqaFNtbnNkTEFkRnMxMnJMS2ZwY0FFUWJtemJ2UHhJX3VRTHFseDhGR1pOQ1FqMEt4cDQyQXJzRjdBOFVoQ0FBekgydVFpa3BOSTRCSFZWUmZMbGc0bjVIYlc4RFF6Z1o?oc=5",
            "pubDate": "Sat, 18 Apr 2026 06:26:53 GMT",
            "source": "The Japan Times"
        },
        {
            "title": "Federal judge blocks Nexstar-Tegna TV station merger until antitrust lawsuit is settled",
            "link": "https://news.google.com/rss/articles/CBMiowFBVV95cUxOX2x1Yzc3WmJNeTRBRURaNDdOWGxHR253d0RMeld0SUdaRjBLeFJVdkFuMTg5b0ZFUGl3S2NVbDM1UURzMDRnYWdiUndaUEhGZS1xNW1yazlONG1wSTdwNU1QXzRJbWFqSDhqWkFSNmpqZ0tmWnpJNjQtcDNubEpTWHZxajgxUWhjWFRjb1FNS1JxOHZNR2pJdzBDZ0prODVDdGVF0gGoAUFVX3lxTFBqQUhsTVR4SEVzR1VwbUVINTRxNFJoU2FzUTc2bjF3S3NGTTU0RHBVWmNseklDRm9lc1owamp2d0gtNDduQU1oU01CQW9GSXJfTnFUanFxZ2hfYUh0UEZxTTZaRUdPWHRfRW5DZTFsSXE4Z2ZITlFveU4xUU90ZjU3YzROSkw3YjA4UlhoYVQ5MEota0JaSlp2X0p5NXlJRExweEdXWEdpcA?oc=5",
            "pubDate": "Sat, 18 Apr 2026 07:23:06 GMT",
            "source": "abcnews.com"
        },
        {
            "title": "Anthropic and Trump: Is a truce near?",
            "link": "https://news.google.com/rss/articles/CBMijgFBVV95cUxNaFRvWUhIaklQSzhsY29iUHVRSHZ5dTBUVGtYZ3VYZWUwbGl6Q1ZWUU4zVGNRWWpRWGZudVNQLUdwMkFPaTl2MDUyY3k0MTlpOVQwSXoydWFpWnlIaDhQU1F3ME5kb2tmd3FOcVA5bFF6OW1NaV9hUDVZLVBYdjBVeTRQYzRSVEp0VjFSbF93?oc=5",
            "pubDate": "Sat, 18 Apr 2026 00:24:45 GMT",
            "source": "Politico"
        },
        {
            "title": "QVC Group, Whose Networks Popularized Shopping On TV, Files For Chapter 11 Bankruptcy",
            "link": "https://news.google.com/rss/articles/CBMikwFBVV95cUxPRDNhdmN1bThYM2Q4akRkWVNEMDhnNWVDREgtaTlYS3FpTXpwX25Ud25pVVNKWkZ6VGtHZnFINFQxNFJ1dzRrU3VfVzF6dFRzYlU1VjRBZ2VsM3lSbjB5NG8yTG1GOHJ5RVEwU1dhZFBWaGloRV9vd1B3dFUyajZFNnNETWlFeWtOZ1h4NjBraHNuc3M?oc=5",
            "pubDate": "Fri, 17 Apr 2026 23:22:00 GMT",
            "source": "Deadline"
        },
        {
            "title": "Wall St Week Ahead Surging record-high US stocks to wade deeper into earnings season",
            "link": "https://news.google.com/rss/articles/CBMiuwFBVV95cUxPaWJmWUFPa2lnWnJCby1JSlA3dU1XVE9YeVpJMTJOSzlzXzI2ZnJqZkREdFlHMENwcldMZFRZaFRkSVlJMm1YdnY4a1ZHN21XRk9kZzFiQW5oYzRxMlJWTHlUNHcxVDR5Ml9UODlxdzNlSDlHVEE3eWR0eFNFOW1YcnI0NzVDZUhjSTdEOHNvWnpLTmJQNTZJZXgwc3RvOWJ4OE94V1N0NnlTV2xpZXFpTHpyUExlX195S19R?oc=5",
            "pubDate": "Fri, 17 Apr 2026 20:22:23 GMT",
            "source": "Reuters"
        },
        {
            "title": "Galaxy S27 Ultra may perform on par with desktops, and not just because of a 2nm chip",
            "link": "https://news.google.com/rss/articles/CBMicEFVX3lxTFB3WWVqWVZXcG1mNFBzcWxNWVBJbE9nQWlfOGRUd3l5T0ItcmxPUUQtY2dBUEhpN2V3ODZLX1ZhVVd3RFN1Q3I2UzNMTnlmWXR0TmYtR0dldmNsSExnYkowbWJvaXhUS2RVSUJWZHR2MC0?oc=5",
            "pubDate": "Thu, 16 Apr 2026 17:08:56 GMT",
            "source": "PhoneArena"
        },
        {
            "title": "Apple's $599 MacBook Neo Sold Out Through April Amid Surging Demand",
            "link": "https://news.google.com/rss/articles/CBMickFVX3lxTE1BYXRiYU8xYzdZazZpRVFPX2dJWmw2U2NZd01RTlhlNXhPX2FsYmgwNFQyTUw2b1d0cFU3OHc5MFRidHFzSGRVNXZTY2RiTXlxUVBabG9ybWhmWjhUSzNNOE54QlA1bHBjRnpzdVd6QTZwdw?oc=5",
            "pubDate": "Thu, 16 Apr 2026 21:01:49 GMT",
            "source": "MacRumors"
        }
    ],
    "technology": [
        {
            "title": "Galaxy S27 Ultra may perform on par with desktops, and not just because of a 2nm chip",
            "link": "https://news.google.com/rss/articles/CBMicEFVX3lxTFB3WWVqWVZXcG1mNFBzcWxNWVBJbE9nQWlfOGRUd3l5T0ItcmxPUUQtY2dBUEhpN2V3ODZLX1ZhVVd3RFN1Q3I2UzNMTnlmWXR0TmYtR0dldmNsSExnYkowbWJvaXhUS2RVSUJWZHR2MC0?oc=5",
            "pubDate": "Thu, 16 Apr 2026 17:08:56 GMT",
            "source": "PhoneArena"
        },
        {
            "title": "Apple's $599 MacBook Neo Sold Out Through April Amid Surging Demand",
            "link": "https://news.google.com/rss/articles/CBMickFVX3lxTE1BYXRiYU8xYzdZazZpRVFPX2dJWmw2U2NZd01RTlhlNXhPX2FsYmgwNFQyTUw2b1d0cFU3OHc5MFRidHFzSGRVNXZTY2RiTXlxUVBabG9ybWhmWjhUSzNNOE54QlA1bHBjRnpzdVd6QTZwdw?oc=5",
            "pubDate": "Thu, 16 Apr 2026 21:01:49 GMT",
            "source": "MacRumors"
        },
        {
            "title": "Ford Mustang GTD Crushes Corvette ZR1X's N\u00fcrburgring Record With 6:40 Lap",
            "link": "https://news.google.com/rss/articles/CBMiiwFBVV95cUxOM195MEJxVGZ6cXdqel9vZE45VDBMWGtHZTkycVh5d3ZZZDV4SzV3NTkyZHQwMFN3TjY0NGRHbHdXYUZJVTBtRmc3R1h0Q1V0bldmWm5CT1J1X3doWDRFZDNwclV4UVdtcVczMF9rNk56bnZEMDV6d0pyTFdITUY0cmJOMk9CQVRhMUsw?oc=5",
            "pubDate": "Sat, 18 Apr 2026 05:32:25 GMT",
            "source": "Motor1.com"
        },
        {
            "title": "Vivo X300 Ultra Review: The Camera King Has Arrived",
            "link": "https://news.google.com/rss/articles/CBMiZkFVX3lxTE1pVEx1cmFjQTBsWWJqUTlyeVlrWTlvRVdaTnVNaFdvMjZLSzN1TEIxaXFFTWY5bmRYeEdsNDZqVnotZXN3MElWbFh5dWUzX3J1dUxHV2s3T0JnOGVCLU9vVFFiT0J6QQ?oc=5",
            "pubDate": "Thu, 16 Apr 2026 15:13:51 GMT",
            "source": "Android Headlines"
        },
        {
            "title": "Amazon will ditch Android on \u2018all\u2019 future Fire TV Sticks as latest model runs Vega OS",
            "link": "https://news.google.com/rss/articles/CBMieEFVX3lxTE5aVkxlTEx0MnNKaEsxaklVMzVFLTZPMFAySW5fdkI5cURVT2psYU1QZlFJelFiZXBOdDA1ZTl6Z1V6U01fLUtGTVhrcDRkOEFXaXVyaTVLUWJJNUZXeWRQcDhDVjc2SmE4c0RnZlVQY3RZOEFsTGdpWQ?oc=5",
            "pubDate": "Fri, 17 Apr 2026 14:25:00 GMT",
            "source": "9to5Google"
        },
        {
            "title": "'WTF Embark' \u2014 Arc Raiders Expedition Changes Leave Players Who Spent Months Saving Millions of Credits Feeling Left Behind",
            "link": "https://news.google.com/rss/articles/CBMimwFBVV95cUxQUDFxNkY3a1Mtd0s3SlYwN1lYb2JPcml3T05RYTZQUk9RMnd0LVZDT05ZSjhkdDlpMnU1elA2dmNDOVpSdlpCRmg5OXcyLTFDMm9VdVQ4Q3pOVHpjUUZTemktMFhTRHFCWjhtXzZGRkVNWXM1bk9CQ2gzTVFJYklNSW5QVW9WN2FycWVjalZ6UHZReElGQnczcTBfSQ?oc=5",
            "pubDate": "Fri, 17 Apr 2026 22:07:43 GMT",
            "source": "IGN"
        },
        {
            "title": "Microsoft Finally Ups FAT32 Size Limit",
            "link": "https://news.google.com/rss/articles/CBMie0FVX3lxTE1YZ3puZE5TR0llLUNhb2cxLUFPSm9jN1daSFotTFJ2cTZnZ1B0eFNHNG9XeHBQNy1kcFFEYmtVaTVhdlBkdWhxY0NiZE1URUdGTXF4S0VjblBrZ19sd0VwRkRzalg4OFo5cXVERjB3MnlaWjF4ZEhzazRtZw?oc=5",
            "pubDate": "Fri, 17 Apr 2026 11:00:00 GMT",
            "source": "Hackaday"
        },
        {
            "title": "Pragmata Launch: Glowing Reviews and Chart-Topping Sales but Mediocre Player Counts",
            "link": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxNWTFVUkhLQzhJd0VUVnMxdnVHTTN3VUJYWGRBYXVTbEFWbmxBazk2ak9CZjFGNWhHQWtDbjRmdTVyenI1ZlNCU2plOEhDa3FvVTV0OE1SMkhKRWxZR1lmSDNrODRka0IxckUxdVN5U2VOUmpDWVdrODktSUlkTVpiRk9XVjQ3RmNEMzZfMEFmZUdOaGFSZG5KSFAybnVZdGZXY2tjTDNHSHRDc0gwbEVIX09OQlZEZWRf0gG-AUFVX3lxTE5mU1d3VE10eXdzdGtkYW41eFQwLXFIUS1SWU96V1RWQ0w3REpGc0V1N3d1b2tKQXF2b0wwc2ZxbWJ4RlA3a3U3d2p4ejdYTkl2U21RbWE0bUFKVkFwQmVpNm9Db2JLSHYydnR3QXZBWm9wNGNwa1RpNkVkQ3Nua2QxcXV2TlhtTlkwX1FFYTdVOHFKdWVQdGp4aG4xQWFQWHhWZUljVDY0b3JPelpQUVhReUlwVkZ6cDFUS2F2amc?oc=5",
            "pubDate": "Fri, 17 Apr 2026 21:28:46 GMT",
            "source": "TechPowerUp"
        },
        {
            "title": "Metro 2039 devs share heartfelt letter with fans after Xbox's reveal of the game, here's what it says",
            "link": "https://news.google.com/rss/articles/CBMi0wFBVV95cUxQUlhMUXpzbDNRZlZvVlluXzl3aWJoZ0FLb29jdWl6Smc5cGRhTm1MSWI3OFhjSmxDTEptX3VMcDRYYUxSV0VzdjhWb1FBSFV4ZTdYN01ZOUMtR1Z2WE8wVkVKTDdpRmk4NHdFdDVCY3ZjZUR4S1ZPemw5ejdxT190QlBkSjBFdnMwczNERnlPZDRFUUNoMlY3V1p1VExWSkQ4Wk42Rlp6TjlXaXpfdDFjZFplWndDaGFuUFplakVNWnQ5YURQdl9CeVpFODJEd0d3R2Qw?oc=5",
            "pubDate": "Thu, 16 Apr 2026 20:43:50 GMT",
            "source": "Windows Central"
        },
        {
            "title": "Tacoma-born inventor of the rolling sneakers known as Heelys dies at 71",
            "link": "https://news.google.com/rss/articles/CBMitAFBVV95cUxQVHo4N292MFVtck0wcnZyeHBxMXRMM1VveVVRS2VvLVRtWkxjaG9TNlg2X0NjVC0wanBhdU00a1JiUHJ4czJWT3lKMjM0Sm8zdWdfbkEyNVJqUUxwV19BY3g1d05Kd0JfaTNpbnA0Nlk3c1FReVY4SnBfWkhwRDAwdndmTkFNS2ViX0FRWGl2ODF4US1qdlg3eERHaGt6ZVJtZnBxdElWMExxNmNjMUhUc29QNGc?oc=5",
            "pubDate": "Thu, 16 Apr 2026 23:13:53 GMT",
            "source": "The Seattle Times"
        },
        {
            "title": "Hackers are abusing unpatched Windows security flaws to hack into organizations",
            "link": "https://news.google.com/rss/articles/CBMitAFBVV95cUxOUlp1MEdPdWlsSnpUZlBzY29CV0JJS1lxZE1nMXh3Wm9qVDFCamJHNTRITDJMVVZsdDJ1QXJ4UzBJdEVqYUFKSGJnSzhVYUpYcmNXelFkR0x4dUhrcW9CU2lzS3VVTVQyczE0UGllQ2xHNWN3bThxZHNISThwZWNCeXQ4dVV3M1plLWFUeXlpMzhsSE8xbXI3Tm1sSWVmV25zTU5BLU9kTElobXJwVHNXOHFOVFo?oc=5",
            "pubDate": "Fri, 17 Apr 2026 17:48:46 GMT",
            "source": "TechCrunch"
        },
        {
            "title": "iPhone 18 Pro release date: Here\u2019s when Apple\u2019s new flagship is coming",
            "link": "https://news.google.com/rss/articles/CBMikwFBVV95cUxQZ1NNQW9MUkFqNmNQcERUd243TEVDUFczN2ZIbkw5ajFJb1ZpSlRCTFBmTlp5Z3BFVk9PeHhzUlJrclZ1SHFxYXZvUnVqOUFRR3dyTDFOVW54VUk3dWRKcTBZbjdycUl1WHFCY0tnTzdwTHBUZmRVdXYtVmF5bDBNempzZ2plYnBma0dhNGs1a2c1cDg?oc=5",
            "pubDate": "Fri, 17 Apr 2026 16:51:00 GMT",
            "source": "9to5Mac"
        },
        {
            "title": "Parents Are Lining Up to Pay $100 for Tin Can\u2019s Screenless, App-Free \u201cLandline\u201d",
            "link": "https://news.google.com/rss/articles/CBMiakFVX3lxTE1LOWRWa3IyWFhyV2ZZZ21UaHI3cE11ZWVqejVYVGdjODZTd1dkRURxT0RQMXVzaGV4MXROTDdScDgyMTMtd2E1LUFKOGZhWFJQTXJTREV0Ym5VYzFpTm0wS25HM3NQNWQ3M0E?oc=5",
            "pubDate": "Thu, 16 Apr 2026 18:05:02 GMT",
            "source": "The New York Times"
        },
        {
            "title": "Fortnite Loses Two Game Modes, But 'Save The World' Goes Free On Xbox & Beyond",
            "link": "https://news.google.com/rss/articles/CBMitgFBVV95cUxPYlROeWxNZmdLWm84VElzODZiSGlnaWlpZTVZTUZNaFpMQ3pyd3Q0al9IODNtSDVwQ3Zaelo0YV9xYXVwQlluUGR4Q24wTUlVVnUyOGNFWGtta3RTWVRzX0VnZUd6aVZXenhreXJ0TU5RSzkyMV9MNVpSUGQ2Q3BBSmlRSlNGTEtUdEYzZk1KZUFxNFdGLUJVZzVDLWtKMWFQLWtkeF9OQUJCNUw4Vnd1d2F3NWpYdw?oc=5",
            "pubDate": "Fri, 17 Apr 2026 13:00:00 GMT",
            "source": "Pure Xbox"
        },
        {
            "title": "It's No Mustang: 911 GT3 RS WIth Manthey Kit Sets N\u00fcrburgring Lap Time",
            "link": "https://news.google.com/rss/articles/CBMiigFBVV95cUxNRzh0TVJPTlUybEtZX2JxTTliMzFwR2pYaDdlOUdlUHI2X1hjdEcwenBhS0xDZE50T1k4c2pkckVJaDUxTVFpbldMdmVUZUljaXM3cDhXME5VS3lFc21qZ0VuZDE5N2dpYjJOYUJUUWZkazBlaXR6ZmtKeU01N2lqZ3Y5blJqeEVFWFE?oc=5",
            "pubDate": "Sat, 18 Apr 2026 06:54:42 GMT",
            "source": "Motor1.com"
        },
        {
            "title": "Tomodachi Life: Living The Dream: Beginner's Guide - Tips & Tricks",
            "link": "https://news.google.com/rss/articles/CBMioAFBVV95cUxOSFUtRU5BS0tqMlg3TDFFT2w5RFBHQ0FvNm5YdWdrRTBvZWp6d1Y0dWFVa3NTUVIzRDZReDNNR2VWTmI4VTFGZnFtc3NUZ0NtejFoMUZadkNmTmx6Y3hERmdRVS1ZeTFIZDhTa1g2aHA5Sld5azdwb2xnQkFsQmRObDlhdXRfZUxXZ1k0Q0ZUMlBwSWY3a3ZaUGgwa015NWZt?oc=5",
            "pubDate": "Fri, 17 Apr 2026 20:18:14 GMT",
            "source": "Nintendo Life"
        },
        {
            "title": "Months-old start-up Recursive Superintelligence raises $500mn for self-teaching AI",
            "link": "https://news.google.com/rss/articles/CBMihAFBVV95cUxNRkEwMlBacDRqNWx6bmFMSFV6cnl5TnI4d3JtNUNGZTZPb0E0a3ROc19lMktEcFFrdEtZZ1BEemRmVl9sRlNIZmFXSDBZTGFjVTlTU0JaSE1VNF81WkdnbU4zQmd3Nmk0WVBwbWJTTm41YV8tQlpjQVNvVTFTWUdGc29VQnU?oc=5",
            "pubDate": "Fri, 17 Apr 2026 21:10:31 GMT",
            "source": "Financial Times"
        },
        {
            "title": "Google Starts Scanning All Your Photos As New Update Goes Live",
            "link": "https://news.google.com/rss/articles/CBMitAFBVV95cUxPb00xNFhJSzF2akRfN2xqVmt0aFlOZ2E0X3Zjb1JHcWtlcDBTeUZwdHE4S3AycjJmcHJkbExVT25jQzFqUlkteG5HanZ5dXdFX2pnV21vRjJuV3lUTUVlWjRHNlk0a2R5UFlSV0JHb2d5bkdYbDdGaDA1Y0p2RENXUU9pdW9mUWdSTHhROU41QTVBNlhNcTN5Tllfejh6eHFHeC1Mc3hvQ3BZVFBxWFpHN1NyeEQ?oc=5",
            "pubDate": "Sat, 18 Apr 2026 09:37:37 GMT",
            "source": "Forbes"
        },
        {
            "title": "Warhammer 40,000 rules reveal \u2013 Shoot from the saddle with Inquisitor Kroyle and Intranzia Fraye",
            "link": "https://news.google.com/rss/articles/CBMi6gFBVV95cUxNY0xEbXJTdzdDUURiS0R6Si0zVzdsbDJpNGZ0V2VpWE9VUkc1Y3ozdUZmYkpueml1U2ktSFBXcy1TNTd6cGhPSXpJT3paOXlJWndnR3NaeWdDNHZQOGJydkd2Y1RnSmczekJ3LV9BWkJja3VZV1RiU2QtVDA4UzY2dlVha0tjN3kzLVFwQXl3ejV5MHlEaGNsV0gxRll1TFJxZmdlMUNjZm9DQTE3OVJGdVYtaXkxd1U1M1I2a3NMUDdjd1hINmdLRWw0UW1iOUtRdFowMWlOeHh3V19QbjdvRjhXMGJLS2laOWc?oc=5",
            "pubDate": "Fri, 17 Apr 2026 14:57:13 GMT",
            "source": "Warhammer Community"
        },
        {
            "title": "25 Things That Screamed, \"They Must Be Rich!\" To People As Kids",
            "link": "https://news.google.com/rss/articles/CBMiiAFBVV95cUxOcEFtTXJ2Z3Q4X2NSWHYzSEhWV2I0aU44Y0JmbkxhajA5ODQxdjllWm1DNTdKcUlKaTAzaVFUX2xfMUd4WW5JTUFaRS1KUzZUcVVBcENPaFVBU09uYW0taWhFa0FlMlFfRzhPZkxSMFY5Q25EX2dPWHZMcGFoRzFkWldSbGJnMlZo?oc=5",
            "pubDate": "Fri, 17 Apr 2026 12:30:02 GMT",
            "source": "BuzzFeed"
        }
    ],
    "gaming": [
        {
            "title": "Long live the \u2018unc game\u2019",
            "link": "https://news.google.com/rss/articles/CBMinwFBVV95cUxQUldlYU5TT2Itang3WjBhRGJKZ2sxNElCQmNxWXhFSXRFR05ka2t0RDUzWkpTZVY2X0QwWldyTi1ucFNQazRkTWtpYnRVajl1czVmdFB2cVloRjlqdTRjZ2kxVklqdUV4S2xGdmszQ2tlMlVwS0tRRjBLY1Z5cFFSZG1TTy1rTEdPQlRTamhoRGFyUjAzTUJqTEdtTHc3X0k?oc=5",
            "pubDate": "Thu, 16 Apr 2026 07:46:00 GMT",
            "source": "The Guardian"
        },
        {
            "title": "Welfare Check for 91-Year-Old Woman Leads Police to Find Her Playing Video Games",
            "link": "https://news.google.com/rss/articles/CBMirAFBVV95cUxON2tZRGMzeVdYTk1IR0VqZHZCeU9sOF91RzJoS0MzZ2Z1Sm1Vc1BjOGZJcEYtVnZtUmZsTlhmZklKMjZ2eUxPZHFPZWtsSXpIZUZQWndqQWN2cmpYem1BTS1LbnN5eGNhV2FZcHVaWGVlY2h1alJTbGJpSU5STGhOeGZwemlwTVdRYXltSUVmSFFEYjdqcENaZ1RTT0xXaXdvWktiaWdvNDNTaWdr?oc=5",
            "pubDate": "Sat, 18 Apr 2026 03:20:27 GMT",
            "source": "People.com"
        },
        {
            "title": "Police rushed to check on a 91-year-old \u2013 and found her gaming",
            "link": "https://news.google.com/rss/articles/CBMiowFBVV95cUxOdF9PYkNzWVg0eExOaUxJR3VHc0lTZ0o0XzNlc05JdEpGM3VZcklGdWRwOTJESmE1QTd1M3ZLYWFLN1E5LWxyR1NXUXV2My1EdkZyWW9LaUs3TUx1VnpERjZHQkNlMkZuM1E3dzlZZ3ZLWWkyS0NIbFlGVFdMREQ4a1RsTy1OQ1VFRGxYYzdpX01vVk5uQ1pwYlRqVG1PYktFU3Vv?oc=5",
            "pubDate": "Sat, 18 Apr 2026 00:23:49 GMT",
            "source": "The Washington Post"
        },
        {
            "title": "91-year-old woman playing video games prompts police welfare check after missing family\u2019s calls",
            "link": "https://news.google.com/rss/articles/CBMixgFBVV95cUxQdGtlUmlPV0hZbzhuaTQyM190Ynlmcl9UaFo5bkhhR2tVbENLUzJYQmlXUGtVeG9JaXhzRzVrNHNSRkZyWTVJd0laeWo4UU9kRGpIVDYwRXBaT0VLYnpEQktKb0MydlRkRC1Jc2g3alYybzkxOW9TbHotd0lSSVFNel9pZ3dsWXVYX2dJNVRrRFNOU3M0a2E1UmlWWDZUcVpBbkV1TnNqUTFZb25wUmpxSHNHMkRhRk1zNDNBaU9wbG82eHdSelHSAdoBQVVfeXFMTUkxUmo3QWFpV2pObnRnQ3ROUXV1VTFidWtGYlpKZW93Y190OEYwRmRrdDJIaUhESkp3TEdCVmxFMUJiWWkyRkJYN1RkVVNZaHM0cDRwR0s4WU4zMWYyWnZ1WU53bTcwR3ZhTkVXUXlDY0RrbUpWbm0wT0Nfdm5RQXRXOVo2alE0SklnNmhpd3ZQM3ZmSE52aHd6b29CV3BUMjdiTHpOTTNhX3JhbHlRNXhvWkUtUVJlVU1IVkxRTDFEeHpMaEc1bTJTTjRvcm5VbnFKYXR6NzFnbGc?oc=5",
            "pubDate": "Fri, 17 Apr 2026 05:30:00 GMT",
            "source": "KLTV.com"
        },
        {
            "title": "15 years after 'Video Games,' Lana Del Rey has an actual video game song",
            "link": "https://news.google.com/rss/articles/CBMitwFBVV95cUxQU19VUjBqU0FrUllDQmN0aF9aQmszR2YwdjhCeUFmLWZCMm1Fa2Y4UE5jZkxvNHg0UjkyRTRZSXRQaEZmTHBqNzNIRXJHRlYteS1JenY5UGRKTExrR0FwOXg5Tl9wem1VdGZNZlhNQ0ZpLVZ0VW0xemJyUi0wOWc3Wjc1azFtWmtqZ1d6cE9GcW5FRmkyOGQzZ2xOeVZNZmVIRnp3RFhUYWd5WGRsRDlXVzJBYTZhOUE?oc=5",
            "pubDate": "Fri, 17 Apr 2026 22:19:25 GMT",
            "source": "Engadget"
        },
        {
            "title": "Everything you want to know about shortform video & games...",
            "link": "https://news.google.com/rss/articles/CBMiekFVX3lxTE5QTlFkMGZjU1JMRUlnUVNyQ3BtcUU5Ry1xcnZfMWJlemtFTDRnXzE2eXBla1VYZ0dGRmRlem9SX08yRTF0Z2hoc1BYdWM5czhab0F0NzdsTFpFZG1KRTM5aWFPTkRPX0hQdFc3bTI2RFl4QV9jcTRvMFVR?oc=5",
            "pubDate": "Fri, 17 Apr 2026 18:50:22 GMT",
            "source": "The GameDiscoverCo newsletter"
        },
        {
            "title": "The Video Games You Should Play This Weekend \u2013 April 17",
            "link": "https://news.google.com/rss/articles/CBMingFBVV95cUxOWW85VkNWa05vQ3RHbE80WHRYa2hQQlZCVmhnNjNKcEsybnQ1ZGVOM2h2U0J1MzRmcnU5UEs1T0hoZmJtNjVPLTFsV2RXWDBZT2pLNFZyX2ZqM216M0VkNW1TMjk0aFdqdVh2N0t0Vm5PbWJDbHdkM3VweGJwRVpMSjZTeDRSRnJsU3dOTmNzS3NJUGRvN3Z0OTBMUmpKQQ?oc=5",
            "pubDate": "Fri, 17 Apr 2026 19:39:13 GMT",
            "source": "Game Informer"
        },
        {
            "title": "VIDEO: Highlights from District 11 all-star basketball games",
            "link": "https://news.google.com/rss/articles/CBMi5gFBVV95cUxPQnN6aDFLSl9kaVJERE9aLUV3SHV4ZFc3STNSc05xMElvZEJSakxlU05mRUpYRW1qNkFfVC1tRGJLVURiTWZvcldiWHB4QXBGbExxUzVhZkpzazc0ZXA0QzhTYVBWZTl0NF95OUlSSEpPUzdCVkxpVzd6aWNUREszc3RlSG8wVmhBMEhNNjdiT2s4Z0puNkM1b3U4VGV0Snl3Q1J2THJzR1QtNk1tQ296WEczUGc0eDgxdEM0SmRySU50dE0yNEVjWTdYN090c1ZkajhGTmxJZEJ1dmotS0xGNkh1WW5ZQQ?oc=5",
            "pubDate": "Sat, 18 Apr 2026 06:12:23 GMT",
            "source": "The Newark Advocate"
        },
        {
            "title": "Game over: Players press EU to ban 'destroying' video titles",
            "link": "https://news.google.com/rss/articles/CBMi6wFBVV95cUxOazFIaHZkd3prNlF4aXNVaWdFbjU2cmp0V09HSDJvbTdRZVhXM3R6R2k0aHJkQVRtWGg2cG5HTk1KRVFlSTFqN1pwZUZPdkhPTjIyU25LVDJUZENwNkpMeWZWMTVsZnZLR3ZQNDFRZkowRmNlZi1xRVQ3MllrZHJFOEJmYmh4UTNxSFpPZERzcmlTWHJVMGhCRmh1ZmlyYWVjZm9iaS11SzZXNUhRV1NpUWZQYWpqLW5PUG9uZVdLd0pvUVRKSGhMTGRPYy1nTGI3aG51Z3ctR3JSaW1zS2hLOC1CZHdLOFJLendN?oc=5",
            "pubDate": "Sat, 18 Apr 2026 09:16:32 GMT",
            "source": "Key Biscayne Portal"
        },
        {
            "title": "Photorealism is hurting video games",
            "link": "https://news.google.com/rss/articles/CBMifEFVX3lxTE9xaVU1LXQ4YlZzZ0ZaMzl4U0UtbFYxV3Z4SWw0Ym9kbjdwTmFDMkpET3k5c25LTnNUdjdaTG5uUnk3a0UxQzFhX2tEdG9SRW9iQWdZU1ZIdFcxSkZLMXRGRUxuNUFEMFVXaS0teU40cWp4NFI3Ym4xb2ZkTGU?oc=5",
            "pubDate": "Tue, 14 Apr 2026 03:24:06 GMT",
            "source": "The Baylor Lariat"
        },
        {
            "title": "Cthulhu: The Cosmic Abyss has one feature that might make me rage quit for good",
            "link": "https://news.google.com/rss/articles/CBMi8AFBVV95cUxNU1JDcjYtZVYwT2V3dktBT2tSWENyQTBOS3dwaVFhM2tjeUx3TzcxUTVwUGNVVndRd3J6TzZrRE5qcVpEX1BiaFprVHpQVzhKWEU5VjA5WkJMT1hSZVA1TzBvbnlncGlnZDRhOXZHT21mSHNWWm45ZHVPUDlLZkJOWE9fVUVZeW05R0JZSk40ZFZnLXFsNXc4ekFFVnpuRmhZOXBnbTRQUGxtYUdGaFNpSUY1a2VEejVkelRRajR2di1leU5mVFpMUWR5US1JRjJsNUZBbWU1d3Vfa19FTEZLSkVuWkpKMU1OVTlkbVJUQnQ?oc=5",
            "pubDate": "Fri, 17 Apr 2026 15:30:00 GMT",
            "source": "TechRadar"
        },
        {
            "title": "Stop Killing Games delivers 'absolutely incredible' hearing in European Parliament: 'There was no [parliament member] that wasn't responding positively'",
            "link": "https://news.google.com/rss/articles/CBMikwJBVV95cUxNcW9HNU02N0ZYOFJsNnBpbF96eWhDd1RObU5sZDBCUTY4SnlhSkQyTUVpSkVCMDI4c04zS21rVTJodEFSeWRmZ0hzT0ptYnozMV9sdUNRZlBUcTJOd2dZYnk2VGZ3Y3BwV3ByS3BDX19oM2JqZ3VZYUgzMDhGNzY0di1PMlppdTA0RlppNEN2UG5SdXQycllsVDZ3Z3FuVmk4OS1neHIzSG4yNFJDRDZ5cnFTWjJRQU9BQjRlcWNUTE9fQlVBNnM0aE5YWmg5RW50Q01HS1ZGeGEyMXdEall0YXh4NHprdkZsNEt6YXo1LVpmQnZQaU4yd2VpdjBFT1hJNlNxbFRjV3JOVk9BZ2lWbE4xaw?oc=5",
            "pubDate": "Fri, 17 Apr 2026 21:50:59 GMT",
            "source": "PC Gamer"
        },
        {
            "title": "Game over: Players press EU to ban 'destroying' video titles",
            "link": "https://news.google.com/rss/articles/CBMi3wFBVV95cUxOWmxIVjJHMWJwaUlLbHF3YUtiTGJuWXkwY0FOa3VJMVQyNEREZFRoNXl5djhwc3VqWERxMWVPT3lNbVkycDlpbjNFTWpLMlpLb3EtZkFuMV93REpITXY4ZFNXSUlJQ25SSlFhV1NYZTRfQVRYOTBXRTMwWjYwSE14RkJLY085cmRvaEhtYUJhTEpwQ3Z5U2dtYjZvaFhJck5NbmJpZVlqUXgwN1dDTmwtNmRsOGpyc0dtRTV0bGZveFpoZFBkZmtWSXNLeTh2a2k0TnBQN25Nc19hampLQzhz?oc=5",
            "pubDate": "Sat, 18 Apr 2026 02:02:07 GMT",
            "source": "Northeast Mississippi Daily Journal"
        },
        {
            "title": "Westlake 91-year-old misses welfare check calls because she was playing video games, police say",
            "link": "https://news.google.com/rss/articles/CBMizwFBVV95cUxOcDVxM0VucHRCdk1FVXFyaEp0T1dEZWtlUF9HbzZlU0hQNjFWQVhKaGJVMndDeW9RWjJsbjFsZ1hMbXFvU3UxZUFGWElxYlpyc2piX2dVTVZWTmo3LW5GajBEUHBzd3A2dEdUbGNWTEhhdWxWNWdsVGRCSVN6YkR1YnFfbU9KRFA4WWZMRF9ESTE0S0pwdUpfZ1NWTmgtQUlEN1NYaUdFOWFyOXlBTzNBX1BERlgxTENMRkVVMDl1akJNcXZmS0VLcDMzeEJndXfSAeMBQVVfeXFMUEVTUTUySGNvdUhKa0JmQlBGXzFTZlhJVTNaYkRsWU1BYXRyWE1KSXc1VkNTeDRWdHU1NElZNHJqeGZXWk5NVGd1c3ktb0NQOUl1Z3pQaEZodHd0VzI3dUlyLUFFVngzSFpQMElWVFZ5MWRSR3lZU3hKT3VMSmZjenRBRXM1eHZKbHhVWFR2MGJjZ0lrcmRhQjhCYnVQOC1QLUh6WkszdkVVdzU4Q3pQYnowQUtuWWlLNXNfcEhrYlBGQ3J6VFpNRXNmSjhpZTUtQ2V0UlBVaHRMZlNHcDRqTTk4d2s?oc=5",
            "pubDate": "Fri, 17 Apr 2026 21:42:00 GMT",
            "source": "Cleveland 19 News"
        },
        {
            "title": "What channel is Knicks vs Hawks today in Game 1 of NBA Playoffs?",
            "link": "https://news.google.com/rss/articles/CBMi3wFBVV95cUxOR2IxOUxxR0hoMTNwSnB2MXBMbVluSDlBOTEtZnAzcWoxU2VESGpDYk1ZNVRZQ0JULTNpMVo5TFNUbkV1d1lVT0tWNnpkOXVxd09McXVWTlExVzZjSE9WMzQ2RFdlQTJkamN4cWFuVHFILThIXzJlN2QxcGo0QVFTNDZVbVhyQ3JJdkUxTWdlNmJYQTVuRW5idUs2eC1jdENIR3ZJUlRQZXJfMkxwNzVzNlYzOEVwNXphZ2w2bEdmMU5qX2VmYUU0YlBUU0pLNUsxN3dWUVVDZGlOTTViTFRJ?oc=5",
            "pubDate": "Sat, 18 Apr 2026 08:01:00 GMT",
            "source": "Bergen Record"
        },
        {
            "title": "Consecration for \u201cClair Obscur: Expedition 33\u201d: the video game developed in Montpellier triumphs at the Bafta Games Awards",
            "link": "https://news.google.com/rss/articles/CBMi4gFBVV95cUxORV9DN0xQMm5jMmdvUGxDRng2ZnowckVxcjlOYk5RNnpuN2dPamV5SXBmYzB3Tm9EbXhzeFg0ZkZIVDZPbHFoekFXMUJhWkNiQWRWUnlyNktHMEdGRVFHNXBjXzJuOXo2R1lPaVJ4MDBwUmdRazFIaE5KaHFPbE1LNWlBZnpReHRoYWFSM0RsNkZGeVVpbkVWdmlDZXRuWjZmMFJLUzNQVVlKZk82bXVPcUdvYm81MFhJQ01nam9IeGd2UnRrM0dWQ2gySjJkTWtLUlQ3WmRYUllaUGNGSEY0V2ZR?oc=5",
            "pubDate": "Sat, 18 Apr 2026 07:56:04 GMT",
            "source": "MVNU"
        },
        {
            "title": "VIDEO: Tommy Lloyd tells Regents 'it's not just about winning basketball games",
            "link": "https://news.google.com/rss/articles/CBMifkFVX3lxTE0zZG9oMFJvRjhVYmxzbVZRN0ZOSURfNWNjbExqNXV0ckZIRWF2RXpxQkZtbXFJLTZDczdNNXpPcHdVVEI1SXNxSUx5TnV2ZG43dVBMSW5ha0dKY29GaVJ5dXpabkdkYXZBcXVGV1VJOGVZeWw4dl8wRGJhZ25aUQ?oc=5",
            "pubDate": "Fri, 17 Apr 2026 23:41:00 GMT",
            "source": "Arizona Daily Star"
        },
        {
            "title": "Bafta Games Awards 2026: A time to celebrate British games?",
            "link": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE94MUJsLVRtLTdkSUNmV3ZmUzJIX0ZrUmNnS2k0cGgzLUQxcEdYRTQ4eWxibnZuT3lHMkFhX2wyRGRmSkRPSUxDRkpMUGd5QjlZak5wby1GT0Nfdw?oc=5",
            "pubDate": "Thu, 16 Apr 2026 23:56:11 GMT",
            "source": "BBC"
        },
        {
            "title": "Senior Ohio woman misses family calls for video games",
            "link": "https://news.google.com/rss/articles/CBMiigFBVV95cUxNXzdNNkRyRTdBRHJ4T1hlZWJ2MkcwWHN1dEplam5SZUFzWFFFUzZoSThzSFd6dUNjc2J3cEhKeFdwYjlVUC1jZFUzMTNFNTFVdnN5a1pyWTRiTmRJaE9Wc25wTjRBNlZyNHVfY25ldVQ1X2RWOWUxQnBrWXlEMmhqcXNDajJuTHBIQ1E?oc=5",
            "pubDate": "Sat, 18 Apr 2026 03:04:00 GMT",
            "source": "Yahoo"
        },
        {
            "title": "... and how gamers can find limits and balance.",
            "link": "https://news.google.com/rss/articles/CBMiowFBVV95cUxOU2Y4S3E0MHk2aHNUTGgtMXVCYmNEZVhnTTlYV19FSElXX0JQMDF1TzNqM2tBbW9UME96S3ZfQWlHNWR4emxLdzM4TFdfOFYwWURkb2ZMMHJzZy0wNUVfUWpGdnFMMFdWa0t1YWFxQkczcFYwN0dkbXI4ZlJPdzQzNS0xWXZlQ0RMZ2poXzg5cm82Mi02dTJQR0F1aFZTX194SWpF0gGoAUFVX3lxTE5LenFQOGVzSG1KUlZxZS1oeXJyQ3NsTnJSWTJEaGhRRVpaaVJJNUxWVm90QkZmQU5CX3Mwc2hoLWF1N3E0TUpmMHEybFNNNF9falhYOGtzbUwxQko0aWViYnpoOG1MZWlRRHkyVzBqRmM1ekNkcDRPbUt3a0F6UmZYSjViSV9OcUpMbmxDbjVPSHBOaU9rNGVFRF9aOVZvYmVVcy05WmFINw?oc=5",
            "pubDate": "Fri, 10 Apr 2026 07:00:00 GMT",
            "source": "Psychology Today"
        }
    ],
    "finance": [
        {
            "title": "Federal judge blocks Nexstar-Tegna TV station merger until antitrust lawsuit is settled",
            "link": "https://news.google.com/rss/articles/CBMiowFBVV95cUxOX2x1Yzc3WmJNeTRBRURaNDdOWGxHR253d0RMeld0SUdaRjBLeFJVdkFuMTg5b0ZFUGl3S2NVbDM1UURzMDRnYWdiUndaUEhGZS1xNW1yazlONG1wSTdwNU1QXzRJbWFqSDhqWkFSNmpqZ0tmWnpJNjQtcDNubEpTWHZxajgxUWhjWFRjb1FNS1JxOHZNR2pJdzBDZ0prODVDdGVF0gGoAUFVX3lxTFBqQUhsTVR4SEVzR1VwbUVINTRxNFJoU2FzUTc2bjF3S3NGTTU0RHBVWmNseklDRm9lc1owamp2d0gtNDduQU1oU01CQW9GSXJfTnFUanFxZ2hfYUh0UEZxTTZaRUdPWHRfRW5DZTFsSXE4Z2ZITlFveU4xUU90ZjU3YzROSkw3YjA4UlhoYVQ5MEota0JaSlp2X0p5NXlJRExweEdXWEdpcA?oc=5",
            "pubDate": "Sat, 18 Apr 2026 07:23:06 GMT",
            "source": "abcnews.com"
        },
        {
            "title": "Anthropic and Trump: Is a truce near?",
            "link": "https://news.google.com/rss/articles/CBMijgFBVV95cUxNaFRvWUhIaklQSzhsY29iUHVRSHZ5dTBUVGtYZ3VYZWUwbGl6Q1ZWUU4zVGNRWWpRWGZudVNQLUdwMkFPaTl2MDUyY3k0MTlpOVQwSXoydWFpWnlIaDhQU1F3ME5kb2tmd3FOcVA5bFF6OW1NaV9hUDVZLVBYdjBVeTRQYzRSVEp0VjFSbF93?oc=5",
            "pubDate": "Sat, 18 Apr 2026 00:24:45 GMT",
            "source": "Politico"
        },
        {
            "title": "QVC Group, Whose Networks Popularized Shopping On TV, Files For Chapter 11 Bankruptcy",
            "link": "https://news.google.com/rss/articles/CBMikwFBVV95cUxPRDNhdmN1bThYM2Q4akRkWVNEMDhnNWVDREgtaTlYS3FpTXpwX25Ud25pVVNKWkZ6VGtHZnFINFQxNFJ1dzRrU3VfVzF6dFRzYlU1VjRBZ2VsM3lSbjB5NG8yTG1GOHJ5RVEwU1dhZFBWaGloRV9vd1B3dFUyajZFNnNETWlFeWtOZ1h4NjBraHNuc3M?oc=5",
            "pubDate": "Fri, 17 Apr 2026 23:22:00 GMT",
            "source": "Deadline"
        },
        {
            "title": "Wall St Week Ahead Surging record-high US stocks to wade deeper into earnings season",
            "link": "https://news.google.com/rss/articles/CBMiuwFBVV95cUxPaWJmWUFPa2lnWnJCby1JSlA3dU1XVE9YeVpJMTJOSzlzXzI2ZnJqZkREdFlHMENwcldMZFRZaFRkSVlJMm1YdnY4a1ZHN21XRk9kZzFiQW5oYzRxMlJWTHlUNHcxVDR5Ml9UODlxdzNlSDlHVEE3eWR0eFNFOW1YcnI0NzVDZUhjSTdEOHNvWnpLTmJQNTZJZXgwc3RvOWJ4OE94V1N0NnlTV2xpZXFpTHpyUExlX195S19R?oc=5",
            "pubDate": "Fri, 17 Apr 2026 20:22:23 GMT",
            "source": "Reuters"
        },
        {
            "title": "Jet fuel supplies are lagging. What does that mean for airlines and travelers?",
            "link": "https://news.google.com/rss/articles/CBMingFBVV95cUxNUUpod1J4UEdDaHlkVDA2YThCYmV1aWZMNjJsdU5GTVFLZTRYaDl4Z19NNmFvRkhkY25PdHh5akVVaElqUmFYNlU3cjNHODE4emlLX21TOXMwM1hZM1lrSjZQdmZiTjRXenhCSVd1T0gzbXNNV2VwMmxCclhXSlJsbnVHbGdRSUZVYURvQ3ZYWHJiRGRNUGo2SW5YQkFkUQ?oc=5",
            "pubDate": "Fri, 17 Apr 2026 20:11:00 GMT",
            "source": "AP News"
        },
        {
            "title": "California coffee chain reinstates policy on Pride flags after swift backlash",
            "link": "https://news.google.com/rss/articles/CBMiiwFBVV95cUxQTi1iM1VRd1Y0aTlhbklUQ3pMN1NoMEJHNV9UdjdwSFRwZ2ptLXJzeGhXMmhqbWNPdm1SWUEwcVBRN0E4OGVZVlFUalBHOG1BaGE4amVHX3c5cTNmYVNTTG9GaUZFOWFwRjJlZlJmczlwZDZpVll1WW5fZW50aS05N0FnbGU2RjB4WGtV?oc=5",
            "pubDate": "Fri, 17 Apr 2026 22:09:00 GMT",
            "source": "The Guardian"
        },
        {
            "title": "Spirit Airlines seeks U.S. government aid as oil spike threatens turnaround",
            "link": "https://news.google.com/rss/articles/CBMic0FVX3lxTE5EemhDQjBGYXlEck4tUlRreTlOVy0xOWVmNzNwTWgwUzFaeksxNzVRSzYxaEFuMEJKUE9IWDlIZ1k3YkRfVWZnWkFlX05SQU10U3ZmUDFDVWdEWUJRYkhXOHpSeTh3UmJSdDFoaktpQ29KVWs?oc=5",
            "pubDate": "Fri, 17 Apr 2026 19:36:10 GMT",
            "source": "The Air Current"
        },
        {
            "title": "American Airlines Rejects United CEO\u2019s Merger Proposal",
            "link": "https://news.google.com/rss/articles/CBMiogFBVV95cUxNbGtZdjI0X3RCdkgyd1pXdmZ1RDN5MGFGTnhSTmllLVNsLUJZYk5tVjhjeW5QYkV0MVc0OERFZ3ZKU2FPaHlld242SV8tOEhEclQ1WG8xRWo2SmxRRFRuakNYRlN4MVAyeTVWZ0pGOVpMSlVsR0l3YkZ5b0FRbFc3ZkhjdHdrWFB2NXhzeXVVZld4d3liWmg0aWMxN1U5S1JtNEE?oc=5",
            "pubDate": "Fri, 17 Apr 2026 22:57:00 GMT",
            "source": "WSJ"
        },
        {
            "title": "Why Netflix Stock Is Tanking Friday",
            "link": "https://news.google.com/rss/articles/CBMingFBVV95cUxOd1FadTJaa0xOTTBIcURfbS1haDR1NHY1MzUtWEpIbjVFNUoySWZrZkRRNU45SUExaXJ1cms0RWxTZzVkdVFRQmVhVHZOdkFJdGZEMDMyNkEtSnhXc0NzOF9GTXY5bXhiUm9FNVlpR1RGR1EyWHpOVFJBNXFtZFdCTTRxNFZ3ZkJMRU4tempQQjF3Ym1PWnh4QVZlZU05UQ?oc=5",
            "pubDate": "Fri, 17 Apr 2026 13:52:40 GMT",
            "source": "Yahoo Finance"
        },
        {
            "title": "Eli Lilly's Pill Lags Novo Nordisk's In First Week. Why Stock Rallied.",
            "link": "https://news.google.com/rss/articles/CBMingFBVV95cUxQeVFVSFhjMExJLWdDRDV1dU5zVHRfcG9WMG51QVN6WEljWnFRMU9tWnlPekdYYkF3bWIyWk9CNjJ0RzJ3SnM2YVp0N0RyeVFfb0g5Q0k4ZmpqVHBXa3luWExENVBNdV9hcDM2Y0ZfS2dvNlpUcHRlV2J1a0x0Wms4NWc1YlpISnZReDBMaGJtU0w2emNQYWNKcUUycGQxZw?oc=5",
            "pubDate": "Fri, 17 Apr 2026 20:10:00 GMT",
            "source": "Investor's Business Daily"
        },
        {
            "title": "O\u2019Hare Must Cut About 300 Flights Per Day This Summer To Reduce Delays, Officials Order",
            "link": "https://news.google.com/rss/articles/CBMixAFBVV95cUxOOEZzOUJsYXNSOTZnMHNjdDFRVERtSWxGd3htekQwZ2pJcUJxcmUzTlRUeGtUbmlSMFFTUC1MSEVkME9xeTBVTnVabHRuSHdiNEFXSDRsbDE1bXQ2VjQzM2xDd0ljak5FT3FPb1VCb1BmMEdKdHZZVHljVE9ubzlRcEhETEIyTkxFUVVpbW5NMi12VW40MDlMelJiY0xtanlHY2Z0NmlSZGdkZC1zLTRaazBleU1mcGdQYWVZZjBxVTZMUmlU?oc=5",
            "pubDate": "Fri, 17 Apr 2026 13:06:50 GMT",
            "source": "Block Club Chicago"
        },
        {
            "title": "Meta layoffs: Tech giant to cut about 8,000 jobs in May, report says",
            "link": "https://news.google.com/rss/articles/CBMihAFBVV95cUxPMHcwY2ZKWWFOT2hMRThVVUJYSE9sbjBrb2xjZ19qaTZhcldhQ3pCc1QzUHlPdkZGTG8yQmQ5N2hTdXA3YmNYcUlKSHVSZWFuWXljQkZITWg5emVIWnJabVVwTk55VFE2UUNfbXR4NE9hQ2lNekFKQm5VWU9qZlNCNjFGSVo?oc=5",
            "pubDate": "Fri, 17 Apr 2026 22:31:55 GMT",
            "source": "San Francisco Chronicle"
        },
        {
            "title": "Kailera CEO 'knew we were in a good spot' before obesity biotech's record-breaking $625M IPO",
            "link": "https://news.google.com/rss/articles/CBMinAFBVV95cUxNZE1YTVB5RTI4U1FIMkpYZUx5Y1BvTUl1UlZaaUN2OGp0MFJ2eDB3NlkxTlFyTEpVYkFlOEh1VTM3QW5hMDJHLVNHd0ZEcjB5Wl9adzZxczZzcmVxZ2R6bXprN2E4RF9Wa3luRVRRYWVkT1JwaWtWU2Nwand5WmIta2ZtZk1QT1pUV2ctay1YSUw1YzVzRTBJblptX0c?oc=5",
            "pubDate": "Fri, 17 Apr 2026 08:42:08 GMT",
            "source": "Fierce Biotech"
        },
        {
            "title": "AI boom is city\u2019s weirdest tech boom, says S.F.\u2019s chief economist",
            "link": "https://news.google.com/rss/articles/CBMif0FVX3lxTE1QdWhZUmI1blp6NkdacmF0czNsRjhtTFI3NnUzUldHdDZaV1dxUGNWd0JKTXZpdG5PU0ZzNlJzVVhweEN5ZFJMMG1QRXZIa3Y3WFhsYWZCYTI4U3cwX25WQlBPWEtuZ0MyMFN1SGtlUzRnSGhqcFlUdzVDaU52TzQ?oc=5",
            "pubDate": "Thu, 16 Apr 2026 21:00:50 GMT",
            "source": "Mission Local"
        },
        {
            "title": "Speech by Governor Waller on the economic outlook",
            "link": "https://news.google.com/rss/articles/CBMid0FVX3lxTE83X2pLZWlBZGdKUTFPbmtvNW16RmRrQVhQY2h6R3VkZHZoczlCYVdkZ1ktOWk1bExtSnYyRVhfdTFRQzdKRnlubzJkcElCMFNRS3doZ0tWbGR1WFZHbmd4Tmg0UWJ4dHF2OXZ5ME9WRlNBVDBhRllV?oc=5",
            "pubDate": "Fri, 17 Apr 2026 18:02:45 GMT",
            "source": "Federal Reserve (.gov)"
        },
        {
            "title": "The attack on Sam Altman exposed a dark underbelly of the anti-AI movement",
            "link": "https://news.google.com/rss/articles/CBMibkFVX3lxTE5lZC0zSWlvQk1KTUhlR1NRREd6Vm5mV2VMRGdHVmktT0V2NTZMeFlSaVVVUzBBUnVTcTlITWVYZVdRM1hwUFByX2w3VU9TTW5BSjR3QWlFR1FlQ2VKUG5zWW9VUGRlWkFmRThnR1Nn?oc=5",
            "pubDate": "Fri, 17 Apr 2026 09:00:55 GMT",
            "source": "CNN"
        },
        {
            "title": "Trump Says Iran Deal Will Bring \u2018Free Oil\u2019 and \u2018Free Hormuz Strait\u2019",
            "link": "https://news.google.com/rss/articles/CBMi-AFBVV95cUxNQWk2UmVkSW4zTUFDNlB4Q0w5MEJydV9GZThVUXE5WllsaUpOMDY0S3N5NTRHVF9PQkZ0YlVZVEZTTEdqRjV5RElmcEtBU0NsbkdydEdneExlcnN6WW02N283VjMwN2F6aE10cDlpRGt1Q2tXLThaT251VTZpYWNGYlpuVEtFelltTkxBZXdHbFdvQkdBMHVYZ0p1RUNDcnVqcEh5SjBnWU5FbFEweWVnbVRBYXVrWmczczhJOUNzcTFaY0RqbmJHUzlHbjJjVjZNZ0FFX3NJc2lJamZSRW9YNTRUalNOTWRaVWxBVkJMQWtkSjVQTmgxTg?oc=5",
            "pubDate": "Thu, 16 Apr 2026 18:31:00 GMT",
            "source": "WSJ"
        },
        {
            "title": "Anthropic debuts Claude Design, because who needs designers?",
            "link": "https://news.google.com/rss/articles/CBMiekFVX3lxTE1rQUp1eGhmbkNEcHhIM3lUX3VtWVQwbDlzVmtSdkdUUDFUUFk4c1FKT3VGWWF6bGUwaEJNU3RfQmJJY3RrZGpHWW94OGFpWDhoeVprdDA1VFhxRmcyaEZYX1l1ek15MklNRkd6VjJsY2IxVHdidGF3ckZn?oc=5",
            "pubDate": "Fri, 17 Apr 2026 20:38:00 GMT",
            "source": "theregister.com"
        },
        {
            "title": "Investors are underestimating global economic impacts of Iran war, top executives warn",
            "link": "https://news.google.com/rss/articles/CBMixwFBVV95cUxNYXZ3YXhPaXBGdnpRSmpYOFdsX3R0ZWE5RzUxaEp3RDY4dlBUc0FSQ29ONkdGb0ZNMUNxcFpWOXJvTmZlOHdnQlQ5a29ialFNcDYyMXlJeUxqenBtWG9JMndCVHB2R3JrdUpKQnVOcmRTS3ZNQkx0ZGdDNV9YMDFEc3JoMlpiUTJhTXczNm1iNnoyNGV2OUo1RHpNckRXWFBwVlFvX2FmaGN6QlY2dzdDanVCMGtTb2hHai1BU3BQalB0Nnl5X3Fv?oc=5",
            "pubDate": "Thu, 16 Apr 2026 21:04:00 GMT",
            "source": "Semafor"
        },
        {
            "title": "Gasoline could drop below $4 in coming days",
            "link": "https://news.google.com/rss/articles/CBMif0FVX3lxTE5STUpRS2ZBcy1naDFTWXNPOExFa21TVmp2WFVCUThBcndzNGx0NTBqZlhBYnZkZ2ItQWwxWEhvZzJJbHZlZ3pZUERieGh3ak1FUlR6WGR4cXhKTkJlZXlRZThsZ3M5RzRLRWFLQUJmT1Y0WnBZWkRlemJBY3h1UlE?oc=5",
            "pubDate": "Fri, 17 Apr 2026 18:47:31 GMT",
            "source": "NPR"
        }
    ]
};
