// Auto-generated multinational news — 2026-04-22T08:12:21.358354Z
// Languages: en, ja, de, fr, es, pt, zh, ko, ar, hi, ru, it, nl, tr, id
window.NEWS_DATA = {
  "en": {
    "local": [],
    "top": [],
    "technology": [],
    "gaming": [],
    "finance": [],
    "sports": [],
    "entertainment": [],
    "health": [],
    "science": [],
    "ai": []
  },
  "ja": {
    "local": [],
    "top": [],
    "technology": [],
    "gaming": [],
    "finance": [],
    "sports": [],
    "entertainment": [],
    "health": [],
    "science": [],
    "ai": []
  },
  "de": {
    "local": [],
    "top": [],
    "technology": [],
    "gaming": [],
    "finance": [],
    "sports": [],
    "entertainment": [],
    "health": [],
    "science": [],
    "ai": []
  },
  "fr": {
    "local": [],
    "top": [],
    "technology": [],
    "gaming": [],
    "finance": [],
    "sports": [],
    "entertainment": [],
    "health": [],
    "science": [],
    "ai": []
  },
  "es": {
    "local": [],
    "top": [],
    "technology": [],
    "gaming": [],
    "finance": [],
    "sports": [],
    "entertainment": [],
    "health": [],
    "science": [],
    "ai": []
  },
  "pt": {
    "top": [],
    "technology": [],
    "gaming": [],
    "finance": [],
    "sports": [],
    "entertainment": [],
    "health": [],
    "science": [],
    "ai": []
  },
  "zh": {
    "top": [],
    "technology": [],
    "gaming": [],
    "finance": [],
    "sports": [],
    "entertainment": [],
    "health": [],
    "science": [],
    "ai": []
  },
  "ko": {
    "top": [],
    "technology": [],
    "gaming": [],
    "finance": [],
    "sports": [],
    "entertainment": [],
    "health": [],
    "science": [],
    "ai": []
  },
  "ar": {
    "top": [],
    "technology": [],
    "gaming": [],
    "finance": [],
    "sports": [],
    "entertainment": [],
    "health": [],
    "science": [],
    "ai": []
  },
  "hi": {
    "local": [],
    "top": [],
    "technology": [],
    "gaming": [],
    "finance": [],
    "sports": [],
    "entertainment": [],
    "health": [],
    "science": [],
    "ai": []
  },
  "ru": {
    "local": [],
    "top": [],
    "technology": [],
    "gaming": [],
    "finance": [],
    "sports": [],
    "entertainment": [],
    "health": [],
    "science": [],
    "ai": []
  },
  "it": {
    "local": [],
    "top": [],
    "technology": [],
    "gaming": [],
    "finance": [],
    "sports": [],
    "entertainment": [],
    "health": [],
    "science": [],
    "ai": []
  },
  "nl": {
    "local": [],
    "top": [],
    "technology": [],
    "gaming": [],
    "finance": [],
    "sports": [],
    "entertainment": [],
    "health": [],
    "science": [],
    "ai": []
  },
  "tr": {
    "local": [],
    "top": [],
    "technology": [],
    "gaming": [],
    "finance": [],
    "sports": [],
    "entertainment": [],
    "health": [],
    "science": [],
    "ai": []
  },
  "id": {
    "local": [],
    "top": [],
    "technology": [],
    "gaming": [],
    "finance": [],
    "sports": [],
    "entertainment": [],
    "health": [],
    "science": [],
    "ai": []
  }
};
