// Auto-generated by fetch_news.py on 2026-04-18T11:23:00.593861Z
window.NEWS_DATA = {
    "top": [
        {
            "title": "Starmer faces calls to resign as UK government admits ambassador to US failed vetting process",
            "link": "https://www.yahoo.com/news/articles/starmer-faces-calls-resign-uk-185204183.html",
            "pubDate": "2026-04-16T18:52:04Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/ap.org/78b4f59d929ddd38689263fb7d211a58",
            "description": ""
        },
        {
            "title": "A world going broke: IMF says America\u2019s $39 trillion national debt is actually a global problem\u2014and AI may be the only rescue",
            "link": "https://finance.yahoo.com/economy/policy/articles/world-going-broke-imf-says-194850050.html",
            "pubDate": "2026-04-16T19:48:50Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/fortune_175/67a9f2c93f636e5466f53007557e4589",
            "description": ""
        },
        {
            "title": "Remains found in car ID'd as family who mysteriously vanished in 1958",
            "link": "https://www.yahoo.com/news/articles/remains-found-car-idd-family-104902556.html",
            "pubDate": "2026-04-17T21:09:01Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/cbs_news_897/03d65b61b9d41b757687e42f206e6762",
            "description": ""
        },
        {
            "title": "New York loses nearly $74 million for not revoking 33,000 illegal licenses for immigrant truckers",
            "link": "https://www.yahoo.com/news/articles/york-loses-nearly-74-million-194641714.html",
            "pubDate": "2026-04-16T19:46:41Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/ap.org/bd17eb9f84f2600836df3f80a9e7a971",
            "description": ""
        },
        {
            "title": "'NYC is cooked': Business leaders and Wall Streeters erupt over proposed luxury second-home tax",
            "link": "https://finance.yahoo.com/economy/policy/articles/nyc-cooked-business-leaders-wall-040201404.html",
            "pubDate": "2026-04-17T04:02:01Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/business_insider_consolidated_articles_886/e7143acf43c849bc1e44ff9021035d17",
            "description": ""
        },
        {
            "title": "Greene says Trump told her if her \u2018son were to get killed,\u2019 it would be her fault",
            "link": "https://www.yahoo.com/news/articles/greene-says-trump-told-her-153036905.html",
            "pubDate": "2026-04-16T15:30:36Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/the_hill_articles_341/6d228c11ea024d49ec3f9e89c003c104",
            "description": ""
        },
        {
            "title": "Kremlin acknowledges criticism after blogger warns Putin 'squeezed' Russians could erupt",
            "link": "https://www.yahoo.com/news/articles/kremlin-acknowledges-criticism-blogger-warns-150531295.html",
            "pubDate": "2026-04-16T15:05:31Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/reuters.com/5f174e7f5f46f640ad984a2146b42d98",
            "description": ""
        },
        {
            "title": "Zelenskiy: Ukraine believes Russia will try again to involve Belarus in the war",
            "link": "https://www.yahoo.com/news/articles/zelenskiy-ukraine-believes-russia-try-174107373.html",
            "pubDate": "2026-04-17T20:36:20Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/reuters.com/5bd363e1bf5e3d7dd5f4a0f78f3aebc7",
            "description": ""
        },
        {
            "title": "Bald eaglets euthanized after being swept from nest during storm",
            "link": "https://www.yahoo.com/news/articles/bald-eaglets-euthanized-being-swept-215218099.html",
            "pubDate": "2026-04-16T21:52:18Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/usa_today_news_641/07b6b4c751065f1fbda084993295193e",
            "description": ""
        },
        {
            "title": "The Supreme Court hands a win to oil and gas companies fighting environmental lawsuits in Louisiana",
            "link": "https://www.yahoo.com/news/articles/us--supreme-court-louisiana-chevron-154606337.html",
            "pubDate": "2026-04-17T15:46:06Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/wgno_new_orleans_283/90487e10d576406d2a0d3c354a9353a7",
            "description": ""
        },
        {
            "title": "US states ranked by how much of their income residents pay in taxes, from least to most",
            "link": "https://finance.yahoo.com/economy/policy/articles/us-states-ranked-much-income-124802533.html",
            "pubDate": "2026-04-16T12:48:02Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/business_insider_consolidated_articles_886/5fe6be1089a9d68b4be8c8db4f24a0d4",
            "description": ""
        },
        {
            "title": "Tyler Robinson, the man accused of killing Charlie Kirk, pushes to ban court cameras claiming biased coverage, attorneys say",
            "link": "https://www.yahoo.com/news/articles/tyler-robinson-man-accused-killing-124019298.html",
            "pubDate": "2026-04-17T12:40:19Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/cnn_articles_875/0f8172d28a11d62a7894d8414b0abb93",
            "description": ""
        },
        {
            "title": "How to Know If Insurance Will Cover Your GLP-1 Medications",
            "link": "https://www.yahoo.com/news/videos/know-insurance-cover-glp-1-125735214.html",
            "pubDate": "2026-04-16T12:57:35Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/nbcu_713/875beecb258dba6e5115cc674ec4e6a3",
            "description": ""
        },
        {
            "title": "I'm an American who lost 100 pounds after moving abroad. A simple habit I started overseas has helped me maintain it.",
            "link": "https://www.yahoo.com/lifestyle/articles/im-american-lost-100-pounds-154401408.html",
            "pubDate": "2026-04-16T15:44:01Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/business_insider_consolidated_articles_886/39f6be583c64939ef7a99c774ebcce4b",
            "description": ""
        },
        {
            "title": "China has \u2018nearly erased\u2019 America\u2019s lead in AI\u2014and the flow of tech experts moving to the U.S. is slowing to a trickle, Stanford report says",
            "link": "https://finance.yahoo.com/sectors/technology/articles/china-nearly-erased-america-lead-184320977.html",
            "pubDate": "2026-04-16T18:43:20Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/fortune_175/94e0edf1a41375ab2a9db6242d688e37",
            "description": ""
        },
        {
            "title": "Artemis astronaut describes charring on heat shield during crew's fiery return to Earth",
            "link": "https://www.yahoo.com/news/articles/artemis-astronaut-describes-charring-heat-222153216.html",
            "pubDate": "2026-04-16T22:21:53Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/reuters.com/6b55e768dc5b553d99dd99e19ebcab54",
            "description": ""
        },
        {
            "title": "Trump has no plan to cut the $39 trillion national debt, but he does want to cut childcare. His budget director is scrambling to clarify",
            "link": "https://www.yahoo.com/news/articles/trump-no-plan-cut-39-142136114.html",
            "pubDate": "2026-04-16T14:21:36Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/fortune_175/25ca173dc2153cb5b056c8d38bc203f8",
            "description": ""
        },
        {
            "title": "Beshear says Vance forgetting commandments to not worship false idols, tell lies",
            "link": "https://www.yahoo.com/news/articles/beshear-says-vance-forgetting-commandments-162217336.html",
            "pubDate": "2026-04-16T16:22:17Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/the_hill_articles_341/5363e711ef68d430cffa94fe80de0803",
            "description": ""
        },
        {
            "title": "Kremlin says Europe's drone cooperation with Ukraine shows its growing involvement in the war",
            "link": "https://www.yahoo.com/news/articles/kremlin-says-europes-drone-cooperation-122526053.html",
            "pubDate": "2026-04-17T12:25:26Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/reuters.com/c0a88265ef148ceaa98e736c1fefe5d9",
            "description": ""
        },
        {
            "title": "I've lived in China for over 10 years and saw the OpenClaw craze unfold. The West needs to keep up.",
            "link": "https://tech.yahoo.com/ai/articles/ive-lived-china-over-10-040801942.html",
            "pubDate": "2026-04-17T04:08:01Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/business_insider_consolidated_articles_886/93d6f1c1aecd9b8f5289205c47b5f655",
            "description": ""
        }
    ],
    "technology": [
        {
            "title": "Once close enough for an acquisition, Stripe and Airwallex are now going after each other",
            "link": "https://techcrunch.com/2026/04/17/once-close-enough-for-an-acquisition-stripe-and-airwallex-are-now-going-after-each-other/",
            "pubDate": "Sat, 18 Apr 2026 05:20:11 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "For most of its life, Airwallex and Stripe have mostly operated in different geographies, selling to different buyers. That's changing."
        },
        {
            "title": "Sam Altman\u2019s project World looks to scale its human verification empire. First stop: Tinder.",
            "link": "https://techcrunch.com/2026/04/17/sam-altmans-project-world-looks-to-scale-its-human-verification-empire-first-stop-tinder/",
            "pubDate": "Fri, 17 Apr 2026 22:34:02 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "World, which has raised eyebrows (but also a lot of interest) with its Orb-centered anonymous verification project, is looking to expand its influence via a bevy of new partners..."
        },
        {
            "title": "Kevin Weil and Bill Peebles exit OpenAI as company continues to shed \u2018side quests\u2019",
            "link": "https://techcrunch.com/2026/04/17/kevin-weil-and-bill-peebles-exit-openai-as-company-continues-to-shed-side-quests/",
            "pubDate": "Fri, 17 Apr 2026 20:38:17 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "Kevin Weil and Bill Peebles are leaving OpenAI as the company shuts down Sora and folds its science team, signaling a sharp pivot away from consumer moonshots toward enterprise AI."
        },
        {
            "title": "Man who hacked US Supreme Court filing system sentenced to probation",
            "link": "https://techcrunch.com/2026/04/17/man-who-hacked-us-supreme-court-filing-system-sentenced-to-probation/",
            "pubDate": "Fri, 17 Apr 2026 20:16:13 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "Nicholas Moore hacked into three U.S. government networks using stolen credentials, and then bragged about it and posted victims' personal data on Instagram under the handle @ih..."
        },
        {
            "title": "Sources: Cursor in talks to raise $2B+ at $50B valuation as enterprise growth surges",
            "link": "https://techcrunch.com/2026/04/17/sources-cursor-in-talks-to-raise-2b-at-50b-valuation-as-enterprise-growth-surges/",
            "pubDate": "Fri, 17 Apr 2026 19:17:26 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "Returning backers a16z and Thrive are expected to lead the round."
        },
        {
            "title": "\u2018Tokenmaxxing\u2019 is making developers less productive than they think",
            "link": "https://techcrunch.com/2026/04/17/tokenmaxxing-is-making-developers-less-productive-than-they-think/",
            "pubDate": "Fri, 17 Apr 2026 18:42:45 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "There's a lot more code \u2014 but it's a lot more expensive and requires a lot more rewriting."
        },
        {
            "title": "Hackers are abusing unpatched Windows security flaws to hack into organizations",
            "link": "https://techcrunch.com/2026/04/17/hackers-are-abusing-unpatched-windows-security-flaws-to-hack-into-organizations/",
            "pubDate": "Fri, 17 Apr 2026 17:48:46 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "A security researcher published details of three security vulnerabilities in Windows Defender, and the code used to exploit them. Now, hackers are taking advantage of the vulner..."
        },
        {
            "title": "Zoom teams up with World to verify humans in meetings",
            "link": "https://techcrunch.com/2026/04/17/zoom-teams-up-with-world-to-verify-humans-in-meeting/",
            "pubDate": "Fri, 17 Apr 2026 17:15:00 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "Meeting platform Zoom has announced a partnership with World, Sam Altman's human ID verification company, to ensure that the people attending meetings are actually human and not..."
        },
        {
            "title": "Gigs turns your concert history into a personal live music archive",
            "link": "https://techcrunch.com/2026/04/17/gigs-turns-your-concert-history-into-a-personal-live-music-archive/",
            "pubDate": "Fri, 17 Apr 2026 16:55:45 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "New iPhone app Gigs uses AI to turn old tickets, screenshots, and emails into a personal concert archive with stats, memories, and more."
        },
        {
            "title": "Chef Robotics escaped the robot cooking graveyard and says it\u2019s thriving \u2014 here\u2019s why",
            "link": "https://techcrunch.com/2026/04/17/chef-robotics-escaped-the-robot-cooking-graveyard-and-says-its-thriving-heres-why/",
            "pubDate": "Fri, 17 Apr 2026 16:15:50 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "The company, which deploys AI-guided robot arms for food production, says it is looking to expand its services to provide for a broader array of customers."
        },
        {
            "title": "Uber will now pick up your returns from your doorstep",
            "link": "https://techcrunch.com/2026/04/17/uber-will-now-pick-up-your-returns-from-your-doorstep/",
            "pubDate": "Fri, 17 Apr 2026 15:02:00 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "The new returns feature is the company's latest effort to become an everything app. There are limitations to the new service, and there is, of course, a courier fee."
        },
        {
            "title": "Anthropic launches Claude Design, a new product for creating quick visuals",
            "link": "https://techcrunch.com/2026/04/17/anthropic-launches-claude-design-a-new-product-for-creating-quick-visuals/",
            "pubDate": "Fri, 17 Apr 2026 15:00:00 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "The company says Claude Design is intended to help people like founders and product managers without a design background share their ideas more easily."
        },
        {
            "title": "With US spy laws set to expire, lawmakers are split over protecting Americans from warrantless surveillance",
            "link": "https://techcrunch.com/2026/04/17/with-us-spy-laws-set-to-expire-lawmakers-are-split-over-protecting-americans-from-warrantless-surveillance/",
            "pubDate": "Fri, 17 Apr 2026 14:00:00 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "Some lawmakers are calling for widespread reforms following years of surveillance scandals and abuses across successive U.S. administrations. But even if the spy law known as Se..."
        },
        {
            "title": "Google\u2019s AI Mode can now help you find products in stock nearby",
            "link": "https://techcrunch.com/2026/04/17/googles-ai-mode-can-now-help-you-find-products-in-stock-nearby/",
            "pubDate": "Fri, 17 Apr 2026 14:00:00 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "Although you can already track hotel prices at the city level, the new update lets you do so for a specific hotel that you're interested in."
        },
        {
            "title": "Bluesky confirms DDoS attack is cause of continued app outages",
            "link": "https://techcrunch.com/2026/04/17/its-not-just-you-bluesky-is-sorta-down/",
            "pubDate": "Fri, 17 Apr 2026 13:22:04 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "Bluesky has been experiencing ongoing service disruptions since just before 3 a.m. ET on April 15."
        },
        {
            "title": "Netflix plans to add a vertical video feed, use AI for recommendations",
            "link": "https://techcrunch.com/2026/04/17/netflix-plans-to-add-a-vertical-video-feed-use-ai-for-recommendations/",
            "pubDate": "Fri, 17 Apr 2026 13:17:18 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "Netflix is going to launch a TikTok-like vertical video feed within its apps this month, and plans to use AI broadly for content creation and recommendations."
        },
        {
            "title": "SaySo is a new short-form video app that aims to restore users\u2019 trust in news",
            "link": "https://techcrunch.com/2026/04/17/sayso-is-a-new-short-form-video-app-that-aims-to-restore-users-trust-in-news/",
            "pubDate": "Fri, 17 Apr 2026 13:00:00 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "Users are fed up with misinformation and AI slop cluttering their feeds. SaySo is a new short-form video app that delivers news from vetted creators and journalists."
        },
        {
            "title": "Loop raises $95M to build supply chain AI that predicts disruptions",
            "link": "https://techcrunch.com/2026/04/17/loop-raises-95m-to-build-supply-chain-ai-that-predicts-disruptions/",
            "pubDate": "Fri, 17 Apr 2026 13:00:00 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "The San Francisco startup closed a Series C funding round led by Antonio Gracias' firm Valor, which is a major backer of xAI."
        },
        {
            "title": "Are we\u00a0tokenmaxxing\u00a0our way to nowhere?",
            "link": "https://techcrunch.com/video/are-we-tokenmaxxing-our-way-to-nowhere/",
            "pubDate": "Fri, 17 Apr 2026 13:00:00 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "The gap between AI insiders and everyone else&#160;is widening, and the spending, suspicion, and even new vocabulary are starting to show it. While OpenAI is busy buying up ever..."
        },
        {
            "title": "New leaders, new fund: Sequoia has raised $7B to expand its AI bets",
            "link": "https://techcrunch.com/2026/04/16/new-leaders-new-fund-sequoia-has-raised-7b-to-expand-its-ai-bets/",
            "pubDate": "Fri, 17 Apr 2026 02:55:06 +0000",
            "source": "TechCrunch",
            "image": "",
            "description": "The fundraise is the first major capital raise under Sequoia's new leadership, with Alfred Lin and Pat Grady now serving as co-stewards of the 54-year-old firm."
        }
    ],
    "gaming": [
        {
            "title": "Samson Coming To Consoles This Fall",
            "link": "https://www.ign.com/articles/samson-coming-to-consoles-this-fall",
            "pubDate": "Fri, 17 Apr 2026 23:40:33 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2026/04/17/liquidswords-samson-handtohandcombat-01-1776469224561.png",
            "description": "Samson, the 1990s-set, gritty open-world action-adventure/brawler directed by Just Cause creator Christofer Sundberg that suffered a buggy release on PC earlier this month, is c..."
        },
        {
            "title": "John Rambo: David Harbour Cast as Commanding Officer Major Trautman",
            "link": "https://www.ign.com/articles/john-rambo-david-harbour-cast-as-commanding-officer-major-trautman",
            "pubDate": "Fri, 17 Apr 2026 23:33:35 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2026/04/17/david-harbour-1776467684886.png",
            "description": "Stranger Things alum David Harbour has reportedly joined the cast of Lionsgate and Millennium Media\u2019s franchise prequel, John Rambo."
        },
        {
            "title": "Arc Raiders Players are Disappointed in the New Expedition Changes",
            "link": "https://www.ign.com/articles/arc-raiders-players-are-disappointed-in-the-new-expedition-changes",
            "pubDate": "Fri, 17 Apr 2026 22:07:40 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2026/03/17/arc-raiders-march-1773758300338.png",
            "description": "Embark Studios has once again announced tweaks to the Arc Raiders Expedition window, and players who have spent months saving millions of credits are feeling left behind."
        },
        {
            "title": "Hulu to Adapt Penn Cole\u2019s Spark of the Everflame Romantasy Series",
            "link": "https://www.ign.com/articles/hulu-to-adapt-penn-coles-spark-of-the-everflame-romantasy-series",
            "pubDate": "Fri, 17 Apr 2026 21:48:25 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2026/04/17/81fsbxyyofl-uf10001000-ql80-1776460115293.jpg",
            "description": "Preparations for the romantasy invasion continue, with Hulu snapping up the rights to adapt the Kindred\u2019s Curse Saga, authored by Penn Cole"
        },
        {
            "title": "KPop Demon Hunters Cast Reunites for Special Online Performances",
            "link": "https://www.ign.com/articles/kpop-demon-hunters-cast-reunites-for-special-online-performances",
            "pubDate": "Fri, 17 Apr 2026 21:40:03 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2025/07/31/kpop-demon-hunters-1-1753979873881.png",
            "description": "The stars behind the anime smash KPop Demon Hunters are reuniting for special online performances as part of the McDonald's Battle Of The Bands collaboration"
        },
        {
            "title": "Clair Obscur: Expedition 33 Wins Best Game at the BAFTA Games Awards 2026",
            "link": "https://www.ign.com/articles/bafta-game-awards-2026-winners",
            "pubDate": "Fri, 17 Apr 2026 20:23:43 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2026/04/17/gettyimages-2271835562-1776457372228.jpg",
            "description": "BAFTA Games Awards 2026 Winners: The Full List."
        },
        {
            "title": "The Last of Us Adds Sinners Star Li Jun Li to Season 3 Cast",
            "link": "https://www.ign.com/articles/the-last-of-us-adds-sinners-star-li-jun-li-to-season-3-cast",
            "pubDate": "Fri, 17 Apr 2026 20:03:26 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2026/04/17/li-jun-li-1776455284853.png",
            "description": "Sinners star Li Jun Li has reportedly boarded HBO\u2019s The Last of Us Season 3 to play the mother of Seraphite siblings Lev and Yara, Miriam."
        },
        {
            "title": "'90s Eco-Fantasy FernGully: The Last Rainforest Getting Live-Action Remake ",
            "link": "https://www.ign.com/articles/90s-eco-fantasy-ferngully-the-last-rainforest-getting-live-action-remake",
            "pubDate": "Fri, 17 Apr 2026 20:02:04 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2026/04/17/ferngully-1776453723397.jpg",
            "description": "FernGully: The Last Rainforest is getting a live-action remake thanks to Amazon MGM Studios"
        },
        {
            "title": "FFXIV and Jollibee Collaboration Brings New In-Game Chicken Emote, Limited-Time Clothing, and Menu Items",
            "link": "https://www.ign.com/articles/ffxiv-and-jollibee-collaboration-brings-new-in-game-chicken-emote-limited-time-clothing-and-menu-items",
            "pubDate": "Fri, 17 Apr 2026 19:35:48 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2026/04/17/2ca9077926ee36f137c7969e60447b75dcaadf17-0-1776446543062.png",
            "description": "From April 21 to May 31, you can pick up Jollibee's new FFXIV-themed meals or swag and get the emote, too!"
        },
        {
            "title": "Pickmos Publisher Pulls Steam Page Following Pok\u00e9mon Rip-Off Accusations",
            "link": "https://www.ign.com/articles/pickmos-publisher-pulls-steam-page-following-pokemon-rip-off-accusations",
            "pubDate": "Fri, 17 Apr 2026 19:28:24 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2026/04/17/pickmos-1776451000162.png",
            "description": "Pok\u00e9mon fans have spent weeks accusing Pickmos of being a rip-off, and now, publisher Networkgo has stepped in, starting by taking down its Steam page."
        },
        {
            "title": "Skyrim Mod Goes Viral",
            "link": "https://www.ign.com/articles/skyrim-mod-goes-viral",
            "pubDate": "Fri, 17 Apr 2026 18:14:28 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2022/06/27/dragon6-1656365789855.jpg",
            "description": "There have been hundreds of ways you could fight dragons in Skyrim, but have you ever tried engaging them in the marketplace of ideas? Well, a bizarre mod will finally let you d..."
        },
        {
            "title": "Slay the Spire 2 Review-Bombing",
            "link": "https://www.ign.com/articles/slay-the-spire-2-review-bombing",
            "pubDate": "Fri, 17 Apr 2026 17:51:58 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2026/03/06/slaythespire2-earlyaccessreview-blogroll-1772836878749.jpg",
            "description": "Recent Slay the Spire 2 Steam reviews have fallen to \"Mixed\" after a new update triggered a second wave of review bombing."
        },
        {
            "title": "Avengers: Doomsday Cast Update",
            "link": "https://www.ign.com/articles/avengers-doomsday-cast-update",
            "pubDate": "Fri, 17 Apr 2026 17:45:37 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2023/02/03/antmanandthewaspquantumaniacassielangfeaturette-ign-blogroll-1675458208467.jpg",
            "description": "Cassie Lang actor Kathryn Newton has celebrated her return to the Marvel Cinematic Universe with a tiny director\u2019s chair, just like her Avengers father, Ant-Man, received during..."
        },
        {
            "title": "Law & Order: Organized Crime Cancelled",
            "link": "https://www.ign.com/articles/law-order-organized-crime-cancelled",
            "pubDate": "Fri, 17 Apr 2026 16:57:25 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2026/04/17/gettyimages-2150483467-1776444834268.jpg",
            "description": "It might finally be the moment where Christopher Meloni hangs up his Elliot Stabler hat. The actor, who has played the beloved Law & Order character on and off for an incredible..."
        },
        {
            "title": "Star Wars: Marvel Reveals a Forgotten Battle Between Luke Skywalker and Boba Fett",
            "link": "https://www.ign.com/articles/star-wars-marvel-reveals-a-forgotten-battle-between-luke-skywalker-and-boba-fett",
            "pubDate": "Fri, 17 Apr 2026 16:02:03 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2026/04/17/mixcollage-17-apr-2026-11-58-am-889-1776441546130.jpg",
            "description": "Did you know that Luke Skywalker and Boba Fett fought before their fateful showdown in Return of the Jedi? That battle will be chronicled in a new Star Wars: Galaxy's Edge comic."
        },
        {
            "title": "Godzilla Minus Zero Will Bring 'A Whole New Level of Terror,' Director Reveals",
            "link": "https://www.ign.com/articles/godzilla-minus-zero-will-bring-a-whole-new-level-of-terror-director-reveals",
            "pubDate": "Fri, 17 Apr 2026 16:00:00 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2026/04/14/godzilla-thumb-1776210298165.jpg",
            "description": "Godzilla Minus Zero director Takashi Yamazaki says his film will bring \"a whole new level of terror\" to the big screen, promising that audiences will \"feel what it's like to be ..."
        },
        {
            "title": "Gears of War Movie Director Shares Promising Update",
            "link": "https://www.ign.com/articles/gears-of-war-movie-director-shares-promising-update",
            "pubDate": "Fri, 17 Apr 2026 15:24:32 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2025/06/09/ss-682b195f070e866bb5c203bf0694ce45d6f61ff1-1920x1080-1749476635818.jpg",
            "description": "Gears of War movie director David Leitch said he feels optimistic that the film is \u201cgoing to happen\u201d after months without an update for fans."
        },
        {
            "title": "White House Tweets Criticized",
            "link": "https://www.ign.com/articles/white-house-tweets-criticized",
            "pubDate": "Fri, 17 Apr 2026 15:21:02 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2026/04/17/gettyimages-2269592037-1776439245651.jpg",
            "description": "Speaking in a Japanese parliamentary session today, Japan\u2019s Minister for Foreign Affairs, Toshimitsu Motegi, called out the White House for using Nintendo Wii Sports footage wit..."
        },
        {
            "title": "As Deep as the Grave Filmmakers Defend Recreating Val Kilmer Using AI ",
            "link": "https://www.ign.com/articles/as-deep-as-the-grave-filmmakers-defend-recreating-val-kilmer-using-ai",
            "pubDate": "Fri, 17 Apr 2026 15:00:00 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2026/04/17/adatg-ai-val-thumb-1776388183704.jpg",
            "description": "The Dead Speak! And they star in movies too in the upcoming As Deep as the Grave, which features an AI-recreation of Val Kilmer in an important role, despite the actor passing a..."
        },
        {
            "title": "Call of Duty Movie Release Date Announced",
            "link": "https://www.ign.com/articles/call-of-duty-movie-update",
            "pubDate": "Fri, 17 Apr 2026 14:56:36 +0000",
            "source": "IGN",
            "image": "https://assets-prd.ignimgs.com/2026/04/17/ss-8694e5cb8262343c867d8f8edb70526b19b49cf8-1920x1080-1776437770541.jpg",
            "description": "The Call of Duty movie got a significant update at CinemaCon 2026, with a release date confirming it\u2019s just over two years away."
        }
    ],
    "finance": [
        {
            "title": "127-year-old retailer confirms more cuts in 2026",
            "link": "https://finance.yahoo.com/markets/stocks/articles/127-old-retailer-confirms-more-231700401.html",
            "pubDate": "2026-04-16T23:17:00Z",
            "source": "Finance",
            "image": "https://media.zenfs.com/en/thestreet_881/a4c9ceab495e1b0fdd0f8ba8312d42d0",
            "description": ""
        },
        {
            "title": "Toyo Co. Ltd. (TOYO) Appoints Rhone Resch as Chief Strategy Officer to Lead Global Growth",
            "link": "https://finance.yahoo.com/sectors/energy/articles/toyo-co-ltd-toyo-appoints-093027006.html",
            "pubDate": "2026-04-17T09:30:27Z",
            "source": "Finance",
            "image": "https://media.zenfs.com/en/insidermonkey.com/de2f882e57b9093d427a34b5f0bc499f",
            "description": ""
        },
        {
            "title": "Equity fund inflows rise as war\u00a0risks recede, upbeat earnings boost mood",
            "link": "https://finance.yahoo.com/news/equity-fund-inflows-rise-war-095821978.html",
            "pubDate": "2026-04-17T09:58:21Z",
            "source": "Finance",
            "image": "https://media.zenfs.com/en/reuters.com/e07eb131af5f40531f2b82551e9ea5d9",
            "description": ""
        },
        {
            "title": "HELOC and home equity loan rates today, April 17, 2026: Tap your homeownership value in cash",
            "link": "https://finance.yahoo.com/personal-finance/mortgages/article/heloc-home-equity-loan-interest-rates-today-friday-april-17-2026-100000534.html",
            "pubDate": "2026-04-17T10:00:00Z",
            "source": "Finance",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2025-06/eb4e4990-4262-11f0-b61f-fecabc8eb879",
            "description": ""
        },
        {
            "title": "Mortgage and refinance interest rates today, April 17, 2026: Buying power 'better than a year ago'",
            "link": "https://finance.yahoo.com/personal-finance/mortgages/article/mortgage-refinance-interest-rates-today-friday-april-17-2026-100000831.html",
            "pubDate": "2026-04-17T10:00:00Z",
            "source": "Finance",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2024-04/c36fbdb0-0289-11ef-be8f-4e0451f1fa09",
            "description": ""
        },
        {
            "title": "QVC Retail Channel Files Bankruptcy Cut $5 Billion of Debt",
            "link": "https://finance.yahoo.com/news/qvc-shopping-channel-files-bankruptcy-233659483.html",
            "pubDate": "2026-04-17T09:46:16Z",
            "source": "Finance",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2026-04/2ede4db0-3a0e-11f1-8b56-91dbe881a3a8",
            "description": ""
        },
        {
            "title": "Best high-yield savings interest rates today, April 17, 2026 (up to 4.1% APY return)",
            "link": "https://finance.yahoo.com/personal-finance/banking/article/best-high-yield-savings-interest-rates-today-friday-april-17-2026-100000948.html",
            "pubDate": "2026-04-17T10:00:00Z",
            "source": "Finance",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2024-07/822c7220-4eb6-11ef-afbf-4972cf7de987",
            "description": ""
        },
        {
            "title": "Best CD rates today, April 17, 2026 (up to 4.05% APY return)",
            "link": "https://finance.yahoo.com/personal-finance/banking/article/best-cd-rates-today-friday-april-17-2026-100000543.html",
            "pubDate": "2026-04-17T10:00:00Z",
            "source": "Finance",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2024-07/c47b17e2-4f64-11ef-afbf-1041709cf169",
            "description": ""
        },
        {
            "title": "Best money market account rates today, April 17, 2026 (up to 4.01% APY return)",
            "link": "https://finance.yahoo.com/personal-finance/banking/article/best-money-market-account-rates-today-friday-april-17-2026-100000051.html",
            "pubDate": "2026-04-17T10:00:00Z",
            "source": "Finance",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2025-04/0ef34f60-1be6-11f0-a17f-e52542084249",
            "description": ""
        },
        {
            "title": "Morning Brief: 3 takeaways from big bank results",
            "link": "https://finance.yahoo.com/news/morning-brief-3-takeaways-from-big-bank-results-100019077.html",
            "pubDate": "2026-04-17T10:00:19Z",
            "source": "Finance",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2026-02/8324fbe0-09ac-11f1-aff9-c970a730b7b6",
            "description": ""
        },
        {
            "title": "IONQ Stock Trade By Greg Steube Should Raise 'Some Flags,' Says Tracker Made Popular By Nancy Pelosi's Stock Moves",
            "link": "https://finance.yahoo.com/markets/stocks/articles/ionq-stock-trade-greg-steube-094608712.html",
            "pubDate": "2026-04-17T09:46:08Z",
            "source": "Finance",
            "image": "https://media.zenfs.com/en/Benzinga/7954fdd5ec6e6d52f21ce85a37ca7e48",
            "description": ""
        },
        {
            "title": "The stock market's big breakout still needs an under-the-hood check: Chart of the Day",
            "link": "https://finance.yahoo.com/news/the-stock-markets-big-breakout-still-needs-an-under-the-hood-check-chart-of-the-day-100030247.html",
            "pubDate": "2026-04-17T10:00:30Z",
            "source": "Finance",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2026-04/5a13ef60-3849-11f1-b7dd-bbff88553f18",
            "description": ""
        },
        {
            "title": "Is Syntec Optics Holdings (OPTX) One of the Best Performing New Tech Stocks to Buy Right Now?",
            "link": "https://finance.yahoo.com/markets/stocks/articles/syntec-optics-holdings-optx-one-092303163.html",
            "pubDate": "2026-04-17T09:23:03Z",
            "source": "Finance",
            "image": "https://media.zenfs.com/en/insidermonkey.com/e13eafb879d337f843e648dbb91ec2ea",
            "description": ""
        },
        {
            "title": "Here is Why Xanadu Quantum Technologies (XNDU) is a Top Performing New Tech Stock",
            "link": "https://finance.yahoo.com/markets/stocks/articles/why-xanadu-quantum-technologies-xndu-092229088.html",
            "pubDate": "2026-04-17T09:22:29Z",
            "source": "Finance",
            "image": "https://media.zenfs.com/en/insidermonkey.com/6f397e05100d25ea799a24f996c32db4",
            "description": ""
        },
        {
            "title": "Ryde Group (RYDE) Announces Expansion Into Hong Kong Mobility Market",
            "link": "https://finance.yahoo.com/markets/stocks/articles/ryde-group-ryde-announces-expansion-092246676.html",
            "pubDate": "2026-04-17T09:22:46Z",
            "source": "Finance",
            "image": "https://media.zenfs.com/en/insidermonkey.com/ee26c99d2d8e010d2e464a3617da02dd",
            "description": ""
        },
        {
            "title": "Home Depot eyes same-day, next-day delivery site in New York",
            "link": "https://finance.yahoo.com/economy/policy/articles/home-depot-eyes-same-day-094000327.html",
            "pubDate": "2026-04-17T09:40:00Z",
            "source": "Finance",
            "image": "https://media.zenfs.com/en/supply_chain_dive_429/79ddb140945438d7f5f3ed9578aefea5",
            "description": ""
        },
        {
            "title": "New Era Energy (NUAI) Secures $140 Million Combined Financing to Transform Balance Sheet",
            "link": "https://finance.yahoo.com/markets/stocks/articles/era-energy-nuai-secures-140-092228753.html",
            "pubDate": "2026-04-17T09:22:28Z",
            "source": "Finance",
            "image": "https://media.zenfs.com/en/insidermonkey.com/78082d484f228154609bba34b4500bdb",
            "description": ""
        },
        {
            "title": "Tigo Energy (TYGO) Launches Inverter Power Output Control for Midwest Residential Systems",
            "link": "https://finance.yahoo.com/markets/stocks/articles/tigo-energy-tygo-launches-inverter-092156923.html",
            "pubDate": "2026-04-17T09:21:56Z",
            "source": "Finance",
            "image": "https://media.zenfs.com/en/insidermonkey.com/8facf0c4abae46f242c5da87557c4804",
            "description": ""
        },
        {
            "title": "GigaCloud Tech (GCT) Announces Marketplace Initiative With Otto Group",
            "link": "https://finance.yahoo.com/markets/stocks/articles/gigacloud-tech-gct-announces-marketplace-092207295.html",
            "pubDate": "2026-04-17T09:22:07Z",
            "source": "Finance",
            "image": "https://media.zenfs.com/en/insidermonkey.com/89894eca51b93f0a51358ab0620a7463",
            "description": ""
        },
        {
            "title": "Perpetuals.com (PDC) Announces Strategic Initiative to Deploy Next-Gen Agentic AI Infrastructure Platform",
            "link": "https://finance.yahoo.com/sectors/technology/articles/perpetuals-com-pdc-announces-strategic-092135706.html",
            "pubDate": "2026-04-17T09:21:35Z",
            "source": "Finance",
            "image": "https://media.zenfs.com/en/insidermonkey.com/0971d6cd3bf2316b357359295d292af5",
            "description": ""
        }
    ],
    "sports": [],
    "entertainment": [
        {
            "title": "Poll: Americans approve of Jimmy Kimmel's return to TV by a more than 2-to-1 margin",
            "link": "https://www.yahoo.com/entertainment/tv/article/poll-americans-approve-of-jimmy-kimmels-return-to-tv-by-a-more-than-2-to-1-margin-183746388.html",
            "pubDate": "2025-09-30T18:37:46Z",
            "source": "News - Latest News & Headlines",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2025-09/23139e11-9e17-11f0-96c6-70f4b908e44e",
            "description": ""
        },
        {
            "title": "Trump calls Sydney Sweeney's American Eagle 'good jeans' campaign the 'HOTTEST\u2019 ad out there, driving up the company's stock",
            "link": "https://www.yahoo.com/entertainment/celebrity/article/trump-calls-sydney-sweeneys-american-eagle-good-jeans-campaign-the-hottest-ad-out-there-driving-up-the-companys-stock-221428273.html",
            "pubDate": "2025-07-31T22:14:28Z",
            "source": "News - Latest News & Headlines",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2025-08/ec51b290-6ed2-11f0-9bf7-aee5e8ae402d",
            "description": ""
        },
        {
            "title": "Hulk Hogan's roles as movie star, media crusader and MAGA hypeman had a major impact outside of the ring",
            "link": "https://www.yahoo.com/entertainment/celebrity/article/hulk-hogans-roles-as-movie-star-media-crusader-and-maga-hypeman-had-a-major-impact-outside-of-the-ring-184345886.html",
            "pubDate": "2025-07-24T18:43:45Z",
            "source": "News - Latest News & Headlines",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2025-07/a51dc900-68b4-11f0-bdfd-5ceac011739a",
            "description": ""
        },
        {
            "title": "China is taking aim at American movies over Trump's tariffs. Here's why that poses a big risk to Hollywood.",
            "link": "https://www.yahoo.com/news/china-is-taking-aim-at-american-movies-over-trumps-tariffs-heres-why-that-poses-a-big-risk-to-hollywood-194753887.html",
            "pubDate": "2025-04-10T19:47:53Z",
            "source": "News - Latest News & Headlines",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2025-04/af9d2420-163e-11f0-adff-7bad0e0832a1",
            "description": ""
        },
        {
            "title": "How COVID changed America, in 12 charts",
            "link": "https://www.yahoo.com/news/how-covid-changed-america-in-12-charts-163056855.html",
            "pubDate": "2025-03-10T16:30:56Z",
            "source": "News - Latest News & Headlines",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2025-03/0db6e560-fdb6-11ef-a7bf-2a91abf82b77",
            "description": ""
        }
    ],
    "health": [
        {
            "title": "Poll: Only 15% of Americans agree with the unproven claim that Tylenol causes autism",
            "link": "https://www.yahoo.com/news/science/article/poll-only-15-of-americans-agree-with-the-unproven-claim-that-tylenol-causes-autism-203609478.html",
            "pubDate": "2025-10-03T20:36:09Z",
            "source": "News - Latest News & Headlines",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2025-10/d2e5fb20-a084-11f0-bf60-935875491237",
            "description": ""
        },
        {
            "title": "Trump promotes unproven theory about Tylenol and autism. What does the science say?",
            "link": "https://www.yahoo.com/news/science/article/trump-promotes-unproven-theory-about-tylenol-and-autism-what-does-the-science-say-214925073.html",
            "pubDate": "2025-09-22T21:49:25Z",
            "source": "News - Latest News & Headlines",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2025-09/7b3c39f0-97fd-11f0-b7df-cdef5887ee1a",
            "description": ""
        },
        {
            "title": "Chagas disease, a deadly infection caused by \u2018kissing bugs,\u2019 may have taken root in the U.S., researchers say",
            "link": "https://www.yahoo.com/news/us/article/chagas-disease-a-deadly-infection-caused-by-kissing-bugs-may-have-taken-root-in-the-us-researchers-say-223616589.html",
            "pubDate": "2025-09-04T22:36:16Z",
            "source": "News - Latest News & Headlines",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2025-09/e668c7e0-89c3-11f0-bf97-4395432ad753",
            "description": ""
        },
        {
            "title": "Confused by the new COVID vaccine guidelines? Here's what you need to know.",
            "link": "https://www.yahoo.com/news/article/confused-by-the-new-covid-vaccine-guidelines-heres-what-you-need-to-know-183705404.html",
            "pubDate": "2025-08-29T18:37:05Z",
            "source": "News - Latest News & Headlines",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2025-08/a8ccf360-8505-11f0-bcbf-6b57a955d09c",
            "description": ""
        },
        {
            "title": "Making sense of the showdown at the CDC",
            "link": "https://www.yahoo.com/news/politics/article/making-sense-of-the-showdown-at-the-cdc-190824510.html",
            "pubDate": "2025-08-28T19:08:24Z",
            "source": "News - Latest News & Headlines",
            "image": "https://s.yimg.com/os/creatr-uploaded-images/2025-08/a1c55120-843d-11f0-bee3-54fe16ffb6e3",
            "description": ""
        }
    ],
    "science": [
        {
            "title": "Wildfires used to 'go to sleep' at night. Climate change has them burning overtime",
            "link": "https://www.yahoo.com/news/articles/wildfires-used-sleep-night-climate-180121919.html",
            "pubDate": "2026-04-17T18:01:21Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/ap.org/b306aefdea7c7a911fcc9da79d79e296",
            "description": ""
        },
        {
            "title": "Ancient teeth reveal clues to the environment humans\u2019 early ancestors evolved in millions of years ago",
            "link": "https://www.yahoo.com/news/articles/ancient-teeth-reveal-clues-environment-133204763.html",
            "pubDate": "2026-04-17T13:32:04Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/the_conversation_us_articles_815/fc2ef2a12e23dff4c3cc82876a5f4ba5",
            "description": ""
        },
        {
            "title": "I\u2019ve fired one of America\u2019s most powerful lasers \u2013 here\u2019s what a shot day looks like",
            "link": "https://tech.yahoo.com/science/articles/ve-fired-one-america-most-133204206.html",
            "pubDate": "2026-04-17T13:32:04Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/the_conversation_us_articles_815/2b2024ff3142c28c9b1e6d8e404f9054",
            "description": ""
        },
        {
            "title": "Ancient cave, hippo bones found under castle: \"Once-in-a-lifetime discovery\"",
            "link": "https://www.yahoo.com/news/articles/ancient-cave-hippo-bones-found-113543780.html",
            "pubDate": "2026-04-17T13:19:00Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/cbs_news_897/dd2b6e93482f8b2b17e5940ba3f5dc2d",
            "description": ""
        },
        {
            "title": "Five seconds of free fall: Astronauts describe historic moon mission \u2014 and nail-biting return to Earth",
            "link": "https://www.yahoo.com/news/articles/five-seconds-free-fall-astronauts-203305851.html",
            "pubDate": "2026-04-17T12:12:15Z",
            "source": "News - Latest News & Headlines",
            "image": "https://media.zenfs.com/en/cnn_articles_875/ffea203969a434c50f0eef94a722713f",
            "description": ""
        }
    ]
};
