import urllib.request
import xml.etree.ElementTree as ET
import json
import os
import datetime
import re

FEEDS = {
    "top": "https://news.yahoo.com/rss/",
    "technology": "https://techcrunch.com/feed/",
    "gaming": "https://feeds.feedburner.com/ign/news",
    "finance": "https://finance.yahoo.com/news/rss",
    "sports": "https://sports.yahoo.com/rss/",
    "entertainment": "https://news.yahoo.com/rss/entertainment",
    "health": "https://news.yahoo.com/rss/health",
    "science": "https://news.yahoo.com/rss/science"
}

def extract_image_from_item(item):
    # 1. Check media:content
    media_content = item.find('.//{http://search.yahoo.com/mrss/}content')
    if media_content is not None and 'url' in media_content.attrib:
        return media_content.attrib['url']
        
    # 2. Check enclosure
    enclosure = item.find('enclosure')
    if enclosure is not None and 'url' in enclosure.attrib and 'image' in enclosure.attrib.get('type', ''):
        return enclosure.attrib['url']
        
    # 3. Check inside description for img tag
    desc = item.find('description')
    if desc is not None and desc.text:
        match = re.search(r'<img[^>]+src="([^">]+)"', desc.text)
        if match:
            return match.group(1)
            
    return ""

def clean_html_text(html_content):
    if not html_content:
        return ""
    # Remove HTML tags using regex
    text = re.sub(r'<[^>]+>', ' ', html_content)
    text = text.replace('&nbsp;', ' ').replace('&quot;', '"').replace('&amp;', '&').replace('&#39;', "'")
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def fetch_and_parse(url, limit=20):
    items = []
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'})
        with urllib.request.urlopen(req) as response:
            xml_data = response.read()
            root = ET.fromstring(xml_data)
            channel = root.find('channel')
            
            # Try to get publisher name from channel
            site_title_node = channel.find('title')
            site_title = site_title_node.text if site_title_node is not None else "News"
            if "Yahoo" in site_title: site_title = site_title.replace("Yahoo", "").strip()
            if "IGN" in site_title: site_title = "IGN"
            
            for item in channel.findall('item')[:limit]:
                title = item.find('title').text if item.find('title') is not None else ""
                link = item.find('link').text if item.find('link') is not None else ""
                pubDate = item.find('pubDate').text if item.find('pubDate') is not None else ""
                desc_html = item.find('description').text if item.find('description') is not None else ""
                
                img_url = extract_image_from_item(item)
                clean_desc = clean_html_text(desc_html)
                
                source = site_title
                if " - " in title:
                    parts = title.rsplit(" - ", 1)
                    title = parts[0].strip()
                
                if clean_desc.startswith(title):
                    clean_desc = clean_desc[len(title):].strip()
                    if clean_desc.startswith('-'):
                         clean_desc = clean_desc[1:].strip()
                
                if len(clean_desc) > 180:
                    clean_desc = clean_desc[:177] + "..."

                items.append({
                    "title": title,
                    "link": link,
                    "pubDate": pubDate,
                    "source": source,
                    "image": img_url,
                    "description": clean_desc
                })
    except Exception as e:
        print(f"Error fetching {url}: {e}")
    return items

def main():
    print("Starting News Fetch Job...")
    all_news = {}
    
    for category, url in FEEDS.items():
        print(f"Fetching {category} from {url}...")
        parsed_items = fetch_and_parse(url)
        all_news[category] = parsed_items
        
    js_content = f"// Auto-generated by fetch_news.py on {datetime.datetime.utcnow().isoformat()}Z\n"
    js_content += f"window.NEWS_DATA = {json.dumps(all_news, indent=4)};\n"
    
    os.makedirs("NewsCommon", exist_ok=True)
    with open("NewsCommon/news_data.js", "w") as f:
        f.write(js_content)
        
    print("Successfully generated NewsCommon/news_data.js with original publisher images.")

if __name__ == "__main__":
    main()
